feat: add theming with react-navigtation guide
callstack/react-native-paper pull request #1860
Opened 2020-04-24 09:26 UTC by matkoson

### Motivation
#1833 

### Test plan

2020-04-26 12:32 UTC, kaioduarte commented
Hi @matkoson! I'd suggest to add a `title` similar as in [RNW source page](https://github.com/callstack/react-native-paper/blob/master/docs/pages/5.react-native-web.md) otherwise your page will get the filename as title (check in the live preview) and to use kebab case in filename to keep the consistence between existing files.

2020-05-05 13:28 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +Offering different theme options, especially dark/light ones, is currently more and more a standard requirement of the modern mobile application, fortunately both `React Navigation` and `React Native
```suggestion
Offering different theme options, especially dark/light ones, is currently more and more a standard requirement of the modern mobile application. Fortunately, both `React Navigation` and `React Native Paper` support configurable theming out-of-the-box.
```

2020-05-05 13:34 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +To start following with this guide, clone the [repo](https://github.com/matkoson/paperNavigationTheming), and checkout the branch `startingPoint`.
I don't like the idea of telling users to clone the repo to start with the guide. I would prefer to keep this guide simple enough so everyone can understand just by reading it. We can mention at the end that there is a repo with more advanced use cases and if anybody is interested can check it out. What do you think?

2020-05-05 13:35 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +In order for our themes to work, both libraries require a wrapper to be used in the entry point of our application, in this case it is `App.tsx`.
I would not mention specific file names because of the reason I wrote above.

2020-05-05 13:36 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +Fortunately, both `React Navigation` and `React Native Paper` offer very similar API when it comes to theming. We can import default themes in light and dark variants from both. We will do just that
Same as above

2020-05-05 13:39 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +```
```suggestion
```js
```

2020-05-05 13:41 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +Out goal here is to combine those two themes into one, so that we could control the theme for the entire application in a single place.
```suggestion
Our goal here is to combine those two themes into one so that we can control the theme for the entire application in a single place.
```

2020-05-05 13:41 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +```
```suggestion
```js
```

2020-05-05 13:48 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +<code>yarn add deepmerge</code>
```suggestion
`\`\`sh
yarn add deepmerge
`\`\`
```

2020-05-05 13:49 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +<code>yarn add deepmerge</code>
These slashes should be removed. I put it here just because gh automatically converted it to the code block XD

2020-05-05 13:49 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +```
```suggestion
```js
```

2020-05-05 13:50 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +```
```suggestion
```js
```

2020-05-05 13:51 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +Next, we need to pass combined themes into the wrappers. For this part, we use the dark one - `CombinedDarkTheme`.
```suggestion
Next, we need to pass combined themes into the Providers. For this part, we use the dark one - `CombinedDarkTheme`.
```

2020-05-05 13:51 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +If you need help, checkout `darkMode` branch and continue following the guide from this point.
Samee as above

2020-05-05 13:52 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +- [Theming in React Native Paper](https://callstack.github.io/react-native-paper/theming.html)
This should be relative path. Please check in other pages how to do this.

2020-05-05 13:52 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +```
```suggestion
```js
```

2020-05-05 13:55 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +`React Context` proves itself very useful in handling cross-cutting concerns like global theme handling, so we will use just that.
Can we paraphrase these two sentences differently? It's not easy to understand when we first say we need React state and then we say we will use context.

2020-05-05 14:04 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +    ...newLightTheme,
This is incorrect, right?

2020-05-05 14:04 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +      ...newLightTheme.colors,
Same here

2020-05-05 14:05 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +    ...newDarkTheme,
Here

2020-05-05 14:05 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +      ...newDarkTheme.colors,
and here :D

2020-05-05 14:06 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +// App.tsx
Also, I would remove the name of the file from snippets.

2020-05-05 14:07 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +Context is already created for you, all you need to do is import it, as seen above. Now, as logic for switching between themes is ready, we need some UI element to control it. We will use `Paper`'s [
I would show how to build that context, it shouldn't be a lot of work. If the guide gets too long I would shorten the scope of it.

2020-05-05 14:08 UTC, Trancever commented on docs/pages/8. theming with React Navigation.md
> +```
```suggestion
```js
```

2020-05-15 05:40 UTC, jbinda commented on docs/pages/8. theming with React Navigation.md
> +Context is already created for you, all you need to do is import it, as seen above. Now, as logic for switching between themes is ready, we need some UI element to control it. We will use `Paper`'s [
Agreed that it can be helpful

2020-05-15 06:34 UTC, matkoson commented on docs/pages/8. theming with React Navigation.md
> +To start following with this guide, clone the [repo](https://github.com/matkoson/paperNavigationTheming), and checkout the branch `startingPoint`.
I think you both have a point there, I'll definitely adjust the guide, so it wouldn't assume the user wants to clone the repo. I also like the idea of adding headers. Thanks for the review @Trancever, @jbinda . I will re-ask for you review once amends are implemented.

2020-06-19 12:40 UTC, matkoson commented on docs/pages/8. theming with React Navigation.md
> +Fortunately, both `React Navigation` and `React Native Paper` offer very similar API when it comes to theming. We can import default themes in light and dark variants from both. We will do just that
`App.tsx` reference removed.

2020-06-19 12:40 UTC, matkoson commented on docs/pages/8. theming with React Navigation.md
> +In order for our themes to work, both libraries require a wrapper to be used in the entry point of our application, in this case it is `App.tsx`.
`App.tsx` reference removed.

2020-06-19 12:52 UTC, matkoson commented on docs/pages/8. theming with React Navigation.md
> +If you need help, checkout `darkMode` branch and continue following the guide from this point.
Removed

2020-08-31 07:39 UTC, Trancever requested changes

2020-08-31 07:39 UTC, Trancever commented on docs/pages/8. theming-with-react-navigation.md
> +const DetailsScreen = (props: ) => {
There is a missing "}"

2020-08-31 07:39 UTC, Trancever commented on docs/pages/8. theming-with-react-navigation.md
> +           <TouchableOpacity
Can we run prettier on those snippets? Or even on the whole md file. It should then format all of the code blocks

2020-08-31 07:39 UTC, Trancever commented on docs/pages/8. theming-with-react-navigation.md
> +  DefaultTheme as NavigationDefaultTheme,
It should be moved one line up

2020-08-31 07:39 UTC, Trancever commented on docs/pages/8. theming-with-react-navigation.md
> +  setTheme: (customTheme?: PaperTheme) => void,
Later you pass `toggleTheme`. This should be unified cause ts will shout and probably it will break.

2020-08-31 07:39 UTC, Trancever commented on docs/pages/8. theming-with-react-navigation.md
> +          primary: theme?.colors.surface,
Is `?` needed here? I believe useTheme is typed in a way that it always returns a theme Object - if not passed explicitly it will return default one.

2020-08-31 07:39 UTC, Trancever commented on docs/pages/8. theming-with-react-navigation.md
> +![paperGuide1](../assets/screenshots/themingWithReactNavigationDarkLightSwitch.gif)
This didn't load when I built docs locally

2020-08-31 07:42 UTC, Trancever commented
@matkoson Additionally, It would be nice to change the title of the guide. It doesn't look good currently.
![image](https://user-images.githubusercontent.com/18584155/91695141-fb66c380-eb6d-11ea-9f72-0b74e3844ca1.png)

Also, could you change the target branch to master? It will probably mess with git history and there will be many unnecessary changes so it would be awesome if you could recreate the PR or rebase it. 🙏 

And last but not least the guide looks awesome, just a few small adjustments and we will merge it 👍

2020-09-08 10:39 UTC, matkoson commented
Closing, new PR https://github.com/callstack/react-native-paper/pull/2209

2020-09-08 10:39 UTC, closed without merging