feat: add prop focusable to icon adornment
callstack/react-native-paper pull request #2143
Opened 2020-08-20 15:19 UTC by brunohkbx

### Summary
It would be nice being able to control whether the adornment should focus the input. 

### Test plan
1. Open the example app
2. Click on the eye icon in the password input and verify if the input will show the password without being focused.

2020-08-28 10:33 UTC, Trancever requested changes

2020-08-28 10:33 UTC, Trancever commented on src/components/TextInput/Adornment/Icon.tsx
> +  focusable?: Boolean;
Can we rename the prop to something like `forceFocus`? I think `focusable` is not a good prop name because it sounds more like whether icon should be focusable or not and in our case it is always focusable.

2020-08-30 14:32 UTC, brunohkbx commented on src/components/TextInput/Adornment/Icon.tsx
> +  focusable?: Boolean;
Done :+1:

2020-08-31 06:45 UTC, Trancever approved these changes

2020-08-31 07:47 UTC, merged