feat: improve chip accessibility
callstack/react-native-paper pull request #2144
Opened 2020-08-21 14:38 UTC by brunohkbx

### Summary
As described in #2056, the prop `onClose` it's not accessible on iOS.

### Before (Not being possible to focus on the close icon)
![Photo 21-08-20 11 22 34](https://user-images.githubusercontent.com/6487206/90901861-f18cd580-e3a1-11ea-9f68-c5c2b6fbc865.png)

### Fixed
![Photo 21-08-20 11 21 01](https://user-images.githubusercontent.com/6487206/90901905-0d907700-e3a2-11ea-8699-43d84d98d390.png)

![Photo 21-08-20 11 21 35](https://user-images.githubusercontent.com/6487206/90901951-1d0fc000-e3a2-11ea-8db3-ace8383e0da6.png)

### Android kept the same behavior
![WhatsApp Image 2020-08-21 at 11 35 33 (1)](https://user-images.githubusercontent.com/6487206/90902240-8f80a000-e3a2-11ea-83ea-a85af64e83ba.jpeg)

![WhatsApp Image 2020-08-21 at 11 35 33](https://user-images.githubusercontent.com/6487206/90902260-94455400-e3a2-11ea-8806-62a61d520276.jpeg)

### Test plan

1. Open the example app with both Android(TalkBack) and iOS(VoiceOver)
2. Check whether Chip is accessible or not

2020-08-28 10:28 UTC, Trancever requested changes

2020-08-28 10:28 UTC, Trancever commented on src/components/Chip.tsx
> +            accessibilityTraits="button"
Could you add `closeIconAccessibilityLabel` prop with a default value of "Close"? Once it's done it will be good to merge

2020-08-30 15:56 UTC, brunohkbx commented on src/components/Chip.tsx
> +            accessibilityTraits="button"
Done :+1:

2020-08-31 06:41 UTC, Trancever approved these changes

2020-08-31 06:43 UTC, Trancever requested changes

2020-08-31 06:43 UTC, Trancever commented on src/components/Chip.tsx
> +      closeIconAccessibilityLabel,
@brunohkbx Sorry, one more thing. Can we have a default value "Close" for this prop? It would be best to set it with `defaultProps`

2020-08-31 12:26 UTC, brunohkbx commented on src/components/Chip.tsx
> +      closeIconAccessibilityLabel,
Ops! Totally forgot.
Should be good now, thanks.

2020-08-31 12:59 UTC, Trancever approved these changes

2020-08-31 12:59 UTC, merged