feat: Add `imageProps` to Avatar.Image
callstack/react-native-paper pull request #2168
Opened 2020-08-31 07:51 UTC by kamui545

New PR for https://github.com/callstack/react-native-paper/pull/1817

It will allow you to pass any props to the `<Image>` component inside of `Avatar.Image`.
Eg: `defaultSource`, `resizeMode`, etc...

2020-08-31 14:10 UTC, Trancever requested changes

2020-08-31 14:10 UTC, Trancever commented on src/components/Avatar/AvatarImage.tsx
> +  imageProps?: ImageProps;
I think this API is not aligned with the rest of the lib. Can we change `source` prop to accept `ImageSourcePropType` or `({ size: number }) => React.ReactNode`? Then in the render function, we can check if `typeof source === 'function'` and call it or pass it to `Image` just like it is now.

2020-08-31 14:57 UTC, kamui545 commented on src/components/Avatar/AvatarImage.tsx
> +  imageProps?: ImageProps;
Just made the changes, please have a look when you have time, thanks

2020-09-01 06:35 UTC, Trancever approved these changes

2020-09-01 06:39 UTC, Trancever commented on src/components/Avatar/AvatarImage.tsx
> +  imageProps?: ImageProps;
👍

2020-09-01 07:20 UTC, merged

2021-04-07 03:13 UTC, aprilmintacpineda commented
This is misleading, I don't see how I can pass ImageProps to Avatar.Image. The original PR contained these lines:

```diff
+     const { size = defaultSize, source, style, theme, imageProps } = this.props;
```

```diff
+ {...imageProps}
```

which will indeed allow us to pass props to image, such as `onLoad`, `onError`, etc.