refactor: update snackbar class component to functional with hooks
callstack/react-native-paper pull request #2177
Opened 2020-09-02 15:15 UTC by unikvozm

### Summary

A class component for Snackbar is rewritten to a functional one with hooks.

### Test plan

Visually the component looks and works the same as before, but 2 snapshots were updated.

2020-09-03 11:35 UTC, Trancever requested changes

2020-09-03 11:35 UTC, Trancever commented on src/components/Snackbar.tsx
> +  let hideTimeout: ReturnType<typeof setTimeout>;
I think we should keep this variable in `useRef` hook. Now even when you set it to something in the next render it will be undefined again.

2020-09-03 12:21 UTC, unikvozm commented on src/components/Snackbar.tsx
> +  let hideTimeout: ReturnType<typeof setTimeout>;
fixed

2020-09-04 10:30 UTC, Trancever requested changes

2020-09-06 12:06 UTC, unikvozm commented on src/components/__tests__/__snapshots__/Snackbar.test.js.snap
> -        "opacity": 1,
fixed. useLayoutEffect instead of useEffect hook helped to fix the changes

2020-09-15 12:07 UTC, Trancever approved these changes

2020-09-15 12:07 UTC, merged