refactor: update List class components to functional
callstack/react-native-paper pull request #2188
Opened 2020-09-04 09:50 UTC by unikvozm

### Summary

Class components for List are rewritten to functional ones.

### Test plan

2020-09-18 10:21 UTC, OlimpiaZurek commented on src/components/List/ListIcon.tsx
> +    <Icon source={icon} size={24} color={iconColor} />
maybe it would be better to add this to the constant and put it above component `const ICON_SIZE=24;`

2020-09-18 10:43 UTC, OlimpiaZurek commented on src/components/List/ListAccordion.tsx
> +    <ListAccordionGroupContext.Consumer>
I would use ` React.useContext(ListAccordionGroupContext);` hook here.

2020-10-09 08:41 UTC, Trancever requested changes

2020-10-09 08:41 UTC, Trancever commented on src/components/List/ListAccordion.tsx
> +      setExpanded(!expandedState);
Can we change it to `setExpanded(expanded => !expanded)`

2020-10-09 08:41 UTC, Trancever commented on src/components/List/ListAccordion.tsx
> +  const [expandedState, setExpanded] = React.useState<boolean>(
Can we rename `expandedState` to `expanded` ?

2020-10-09 08:41 UTC, Trancever commented on src/components/List/ListAccordionGroup.tsx
> +    setExpandedId(() =>
Can we get the current expandedId like that: `setExpandedId((currentExpandedId) =>` ?

2020-10-27 10:01 UTC, Trancever approved these changes

2020-10-27 10:14 UTC, merged