refactor: update search bar class component to functional
callstack/react-native-paper pull request #2216
Opened 2020-09-09 12:04 UTC by unikvozm

### Summary

SearchBar class component is rewritten as a functional one.

### Test plan

2020-09-11 14:07 UTC, thymikee commented on src/components/Searchbar.tsx
> +    isFocused: () => root.current?.isFocused() || false,
Technically this is a change in behavior. Likely better to tackle as a followup

2020-09-11 14:08 UTC, thymikee commented on src/components/Searchbar.tsx
> +        }}
```suggestion
        ref={root}
```

2020-09-15 12:28 UTC, Trancever requested changes

2020-09-15 12:28 UTC, Trancever commented on src/components/Searchbar.tsx
> +    isFocused: () => root.current?.isFocused() || false,
Let's type the isFocused as `isFocused(): boolean | undefined;` and get rid of the fallback

2020-09-15 12:28 UTC, Trancever commented on src/components/Searchbar.tsx
> +const Searchbar: React.RefForwardingComponent<TextInputHandles, Props> = (
Can we pass native TextInput instead of custom type here?

2020-09-16 11:25 UTC, unikvozm commented on src/components/Searchbar.tsx
> +    isFocused: () => root.current?.isFocused() || false,
native TextInput has isFocused: () => boolean;

2020-10-27 13:01 UTC, Trancever requested changes

2020-10-27 13:01 UTC, Trancever commented on src/components/__tests__/Searchbar.test.js
> +jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper');
This can be deleted after rebase with master

2020-10-28 10:49 UTC, MrMuzyk commented on src/components/__tests__/Searchbar.test.js
> +jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper');
Done

2020-10-28 10:50 UTC, MrMuzyk commented on src/components/Searchbar.tsx
> +      isFocused: () => root.current?.isFocused() || false,
When its not provided by arrow function anymore there is no need for that

2020-10-28 10:50 UTC, MrMuzyk commented on src/components/Searchbar.tsx
> +      focus: () => root.current?.focus(),
done

2020-10-28 12:43 UTC, Trancever requested changes

2020-10-28 12:43 UTC, Trancever commented on src/components/Searchbar.tsx
> +      focus: root && root.current!.focus,
Why do we need to check if `root` is defined? It's the `current` property on `root` that can be nullish, but root should be always truthy.

2020-10-28 13:49 UTC, MrMuzyk commented on src/components/Searchbar.tsx
> +      focus: root && root.current!.focus,
If the `current` property can be nullish then we need to provide default values in such case for types to match

2020-10-28 14:44 UTC, Trancever commented on src/components/Searchbar.tsx
> +      focus: root && root.current!.focus,
Yeah, but `root` is not nullish, which means we should be able to simply `focus: root.current!.focus,`

2020-10-28 14:55 UTC, MrMuzyk commented on src/components/Searchbar.tsx
> +      focus: root && root.current!.focus,
ok, fixed that

2020-10-30 09:06 UTC, Trancever requested changes

2020-10-30 09:06 UTC, Trancever commented on src/components/Searchbar.tsx
> +      focus: root.current!.focus,
Hmm, after looking at it again I think what we are doing here is wrong. We are basically changing the old behaviour and current version will throw an error if `root.current` is nullish for some reason.

I think we should keep the same behaviour as before which means we should only call the function when it is defined and if it is not then we shouldn't (this will throw a typescript error cause return value won't match, but we can silence it with `@ts-ignore`) - `focus: root.current?.focus`

2020-10-30 10:02 UTC, Trancever approved these changes

2020-10-30 10:02 UTC, merged