refactor: update progress bar class component to functional
callstack/react-native-paper pull request #2219
Opened 2020-09-10 08:32 UTC by unikvozm

### Summary

ProgressBar class component is rewritten as a functional one.

### Test plan

2020-09-11 14:20 UTC, thymikee requested changes
Rules of Hooks must be obeyed :)

2020-09-11 14:20 UTC, thymikee commented on src/components/ProgressBar.tsx
> +  }, [width]);
There are numerous hooks warnings here and there. I see they're not automatically "fixed" due to linter config. Please address these warnings in all cases. They'll often require wrapping functions in `useCallback` or so, but it's better to rely on the rules of hooks instead of manually track dependencies.

2020-09-14 08:23 UTC, thymikee commented on src/components/ProgressBar.tsx
> +  });
this will re-run with every render, let's add a dependency array :)

2020-09-18 07:33 UTC, Trancever requested changes

2020-09-18 07:33 UTC, Trancever commented on src/components/ProgressBar.tsx
> +  }, [width, prevWidth, startAnimation, visible]);
I think we don't need to put `width` in the dependency array

2020-09-18 07:44 UTC, thymikee commented on src/components/ProgressBar.tsx
> +  }, [progress, visible, startAnimation, stopAnimation]);
We can remove progress (ESLint should hint you on that) as it's a dependency of `startAnimation`
```suggestion
  }, [visible, startAnimation, stopAnimation]);
```

2020-09-18 07:54 UTC, unikvozm commented on src/components/ProgressBar.tsx
> +  }, [progress, visible, startAnimation, stopAnimation]);
it's strange, but ESLint hinted only about missing dependencies in useEffect(). I'll check manually other components then

2020-09-18 07:59 UTC, thymikee commented on src/components/ProgressBar.tsx
> +  }, [progress, visible, startAnimation, stopAnimation]);
Ah yea, I tend to remove dependencies and regenerate them once in a while. Sounds like something to be improved in the plugin :)

2020-10-27 13:24 UTC, Trancever approved these changes

2020-10-27 13:24 UTC, merged