refactor: update menu class components to functional
callstack/react-native-paper pull request #2221
Opened 2020-09-10 10:37 UTC by unikvozm

### Summary

Menu class components are rewritten as functional ones.

### Test plan

2020-09-15 08:31 UTC, matkoson commented on src/components/__tests__/Menu.test.js
> +it('renders not visible menu', async () => {
Do we need to make those functions async?

2020-09-15 08:56 UTC, unikvozm commented on src/components/__tests__/Menu.test.js
> +it('renders not visible menu', async () => {
without them a warning occurs in tests:
```
 PASS  src/babel/__tests__/index.js

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      247 |     const { animation } = theme;
      248 |     Animated.parallel([
    > 249 |       Animated.timing(scaleAnimation, {
          |                                         ^
      250 |         toValue: { x: menuLayout.width, y: menuLayout.height },
      251 |         duration: ANIMATION_DURATION * animation.scale,
      252 |         easing: EASING,

      at Object.get Dimensions [as Dimensions] (node_modules/react-native/index.js:209:12)
      at show$ (src/components/Menu/Menu.tsx:249:41)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      207 |       // And when menu is dismissed, send focus back to the button to resume tabbing
      208 |       const node: any = findNodeHandle(el);
    > 209 |       const focusableNode = node.querySelector(
          |                  ^
      210 |         // This is a rough list of selectors that can be focused
      211 |         'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
      212 |       );

      at Object.get BackHandler [as BackHandler] (node_modules/react-native/index.js:187:12)
      at removeListeners (src/components/Menu/Menu.tsx:209:18)
      at hide (src/components/Menu/Menu.tsx:296:5)
      at updateVisibility$ (src/components/Menu/Menu.tsx:164:38)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
```

2020-10-30 08:53 UTC, Trancever requested changes

2020-10-30 08:53 UTC, Trancever commented on src/components/__tests__/Menu.test.js
> +jest.useFakeTimers();
Let's rebase with master and remove the mocks.

2020-10-30 08:53 UTC, Trancever commented on src/components/Menu/Menu.tsx
> +  const measureMenuLayout = () =>
Can we keep measureMenu and measureAnchor functions next to each other?

2020-10-30 08:53 UTC, Trancever commented on src/components/Menu/Menu.tsx
> +  const anchor = React.useRef<View | null>(null);
Can we move it to the top of the file where all other hooks are defined? And let's rename it to anchorRef

2020-10-30 08:53 UTC, Trancever commented on src/components/Menu/Menu.tsx
> +  const menu = React.useRef<View | null>(null);
Same as above

2020-10-30 08:53 UTC, Trancever commented on src/components/Menu/Menu.tsx
> +  anchor: anchorProp,
Let's keep using `anchor` name as before and let's rename ref to `anchorRef` to avoid name duplication.

2020-10-30 08:53 UTC, Trancever commented on src/components/Menu/Menu.tsx
> +  const attachListeners = React.useCallback(() => {
attachListeners and removeListeners functions should be also placed next to each other

2021-01-18 14:43 UTC, Trancever commented
I've checked locally and the menu seems to be a bit broken. If the anchor is close to the right edge of the screen, it should animate from the top right corner instead of the top left corner.

2021-01-26 00:10 UTC, closed without merging