[WIP] refactor: update cross fade icon class component to functional
callstack/react-native-paper pull request #2222
Opened 2020-09-10 13:31 UTC by unikvozm

### Summary

CrossFadeIcon class component is rewritten as a functional one.

### Test plan

One test fails:
```
 FAIL  src/components/__tests__/Appbar/Appbar.test.js
  ● Appbar › passes additional props to AppbarBackAction, AppbarContent and AppbarAction

    TypeError: Cannot read property 'size' of undefined

      4 | 
      5 | const AppbarBackIcon = ({
    > 6 |   size = 24,
        |   ^
      7 |   color,
      8 | }: {
      9 |   size?: number;

      at AppbarBackIcon (src/components/Appbar/AppbarBackIcon.tsx:6:3)
      at mountState (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6520:20)
      at Object.useState (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7077:16)
      at Object.useState (node_modules/react/cjs/react.development.js:1619:21)
      at CrossFadeIcon (src/components/CrossFadeIcon.tsx:27:47)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6156:18)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8690:13)
      at beginWork$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10052:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14694:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14667:22)
```

2020-09-18 13:43 UTC, OlimpiaZurek approved these changes

2020-10-09 08:17 UTC, Trancever commented on src/components/CrossFadeIcon.tsx
> +  }, [previousIcon, fade, scale]);
I am not sure if having `previousIcon` in dependency array is enough, it will only compare the object reference. Previously we were checking the equality with the `isEqualIcon` function. @satya164 What do you think about keeping the previous previous icon in the ref and still comparing it with `isEqualIcon` function?

2020-10-09 11:45 UTC, satya164 commented on src/components/CrossFadeIcon.tsx
> +  }, [previousIcon, fade, scale]);
@Trancever sounds good to me.

2020-10-09 11:45 UTC, satya164 commented on src/components/__tests__/FAB.test.js
> +jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper');
Maybe we can add this `NativeAnimatedHelper` mock in a global jest setup file instead of in each test file.

2020-10-23 13:06 UTC, MrMuzyk commented on src/components/__tests__/FAB.test.js
> +jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper');
@unikvozm adviced to separate it into different PR as there are more places in the code thats already on master so here it is https://github.com/callstack/react-native-paper/pull/2309/files

2020-10-23 13:11 UTC, MrMuzyk commented on src/components/__tests__/FAB.test.js
> +jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper');
therefore if the changes above will be merged to master ill simply remove these mocks from this PR

2020-10-27 10:41 UTC, Trancever requested changes

2020-10-27 10:41 UTC, Trancever commented on src/components/CrossFadeIcon.tsx
> +  const previousPreviousIconRef = React.useRef<IconSource | null>();
Can we do:

```suggestion
  const { current: previousPreviousIcon } = React.useRef<IconSource | null>();
```

and remove line 41?

2020-10-27 11:01 UTC, MrMuzyk commented on src/components/CrossFadeIcon.tsx
> +  const previousPreviousIconRef = React.useRef<IconSource | null>();
After changing it to 
```
  let { current: previousPreviousIcon } = React.useRef<IconSource | null>();
  React.useEffect(() => {
    previousPreviousIcon = previousIcon;
  }, [previousIcon]);
```
and removing line 41

Im getting a warning from eslint:
ESLint: Assignments to the 'previousPreviousIcon' variable from inside React Hook React.useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside React.useEffect.(react-hooks/exhaustive-deps)

2020-10-27 11:08 UTC, Trancever commented on src/components/CrossFadeIcon.tsx
> +  const previousPreviousIconRef = React.useRef<IconSource | null>();
Ok then let's keep the ref as it is now, but let's remove line 41 anyway, since `previousPreviousIcon ` is used only once so there's no need to make it and we can directly use `previousPreviousIconRef.current`

2020-10-27 11:10 UTC, MrMuzyk commented on src/components/CrossFadeIcon.tsx
> +  const previousPreviousIconRef = React.useRef<IconSource | null>();
Sure

2020-10-27 11:47 UTC, Trancever approved these changes

2020-10-27 11:47 UTC, merged