Updating Snackbar documentation
callstack/react-native-paper pull request #2229
Opened 2020-09-12 16:07 UTC by juancarlosjr97

Adding to the Snackbar documentation on how to change the color of the action button of a snackbar.

### Summary

I was trying to change the color of the action button on a snackbar. Chatting online with one the developer, it is passing the theme props, changing the `accent` color.

### Test plan

2020-10-26 11:47 UTC, Trancever requested changes

2020-10-26 11:47 UTC, Trancever commented on src/components/Snackbar.tsx
> +                * Change the color of the text of the action of the snackbar passing a theme prop.
This shouldn't be done here. Above the component, we have a commented section that provides an example of the component usage, and we can also add additional information there.

2020-10-30 18:51 UTC, juancarlosjr97 commented on src/components/Snackbar.tsx
> +                * Change the color of the text of the action of the snackbar passing a theme prop.
Sorry, where above @Trancever ?? Can you tell so I can make the change, please.

2020-11-10 13:41 UTC, Trancever commented on src/components/Snackbar.tsx
> +                * Change the color of the text of the action of the snackbar passing a theme prop.
Check line 60

2020-12-08 09:39 UTC, Trancever commented
@juancarlosjr97 Please reopen the PR if it is still relevant. I am closing because of inactivity and conflicts.

2020-12-08 09:39 UTC, closed without merging