React navigation app bar guide
callstack/react-native-paper pull request #2248
Opened 2020-09-21 11:54 UTC by haxonadora

Added react-navigation and react-native-paper App bar integration guide

2020-10-20 07:05 UTC, Trancever requested changes
It's looking really good! A couple of small issues but nothing really big.

One thing that I would like to ask you is to go through the whole text once again and check it with google or some other translator. Also, there are many sentences starting with a "Now" word. Can they be rephrased to make the article look and sound more professional?

2020-10-20 07:05 UTC, Trancever commented on docs/pages/9.react-navigation.md
> +We can easily add additional actions with `Appbar.Action` to our app. For example menu button and let's make it render only on the main screen.
Can we somehow rephrase the second sentence? It's not really understandable to me  :D

2020-12-07 12:44 UTC, raajnadar commented on docs/pages/9.react-navigation.md
> +We also want our manu to appear only on `HomeScreen`, so we will check if `previous` props is available:
Typo: manu -> menu

2020-12-10 12:54 UTC, Trancever requested changes

2020-12-10 12:54 UTC, Trancever commented on docs/pages/9.react-navigation.md
> +We assume that you already have installed libraries above and if that is not the case please check out the guides below.
```suggestion
We assume that you have already installed the mentioned libraries and if that is not the case please check out the guides below.
```

2020-12-10 12:54 UTC, Trancever commented on docs/pages/9.react-navigation.md
> +We can start using react-navigation by creating a basic navigation stack. Stack navigator gives us possibility to transition between screens in our app and manage navigation's history. In a simple sc
```suggestion
We will start with react-navigation by creating a basic navigation stack. Stack navigator gives us a possibility to transition between screens in our app and manage navigation's history. In a simple scenario where there is only one stack navigator present in the app, it resembles a navigation state in a browser.
```

2020-12-10 12:54 UTC, Trancever commented on docs/pages/9.react-navigation.md
> +When user navigates in the app it pushes or pops items to stack and different screens are displayed.
```suggestion
When the user navigates in the app, it pushes to stack or pops from the stack and different screens are presented.
```

2020-12-10 12:54 UTC, Trancever commented on docs/pages/9.react-navigation.md
> +Once we have that we can run the app and check how Stack looks like.
```suggestion
Once we have finished implementing the components, we can run the app and check how Stack looks like.
```

2020-12-10 12:54 UTC, Trancever commented on docs/pages/9.react-navigation.md
> +To navigate from `HomeScreen` to `DetailsScreen` we can use navigation object provided by `Stack.Screen` component. Every component rendered by `Stack.Screen` has access to navigation object via prop
```suggestion
To navigate from `HomeScreen` to `DetailsScreen` we can use the navigation object provided by `Stack.Screen` component. Every component rendered by `Stack.Screen` has access to navigation object via props. Let's modify our `HomeScreen` component:
```

2020-12-10 12:54 UTC, Trancever commented on docs/pages/9.react-navigation.md
> +As you can see, we can already navigate between two screens. In the next steps we will show you how to use Paper's `AppBar` instead of the default header.
```suggestion
As you can see, we can already navigate between two screens. In the next steps, we will show you how to use Paper's `AppBar` instead of the default header.
```

2020-12-10 12:54 UTC, Trancever commented on docs/pages/9.react-navigation.md
> +Now we can implement `CustomNavigationBar` using `AppBar`:
```suggestion
Now we will implement `CustomNavigationBar` using `AppBar` component:
```

2020-12-10 12:54 UTC, Trancever commented on docs/pages/9.react-navigation.md
> +We want to see application title on the main screen and back arrow button on other screens. We can pass navigation props to our `CustomNavigationBar` component. This way we can know if we are on the
```suggestion
Our current implementation of the `CustomNavigationBar` is very simple, we just render a title inside of it. There is currently no way to go back to the previous screen because the back button is not visible in the header. Let's add it now and let's make sure it's visible on all Stack's screens except `Home` screen.
```

2020-12-10 12:54 UTC, Trancever commented on docs/pages/9.react-navigation.md
> +First let's pass navigation props to `CustomNavigationBar`:
```suggestion
First, let's pass navigation props to `CustomNavigationBar`:
```

2020-12-10 12:54 UTC, Trancever commented on docs/pages/9.react-navigation.md
> +For the next step we check if navigation has previous state. If it has, we can render back arrow button, otherwise we will render app name as before.
```suggestion
As a second step, we check if navigation has previous state. If it has, it means there is another screen on the stack beneath the current screen and we should render the back arrow button in such a case.
```

2020-12-10 12:54 UTC, Trancever commented on docs/pages/9.react-navigation.md
> +We also want our manu to appear only on `HomeScreen`, so we will check if `previous` props is available:
```suggestion
We also want the menu to appear only on `HomeScreen`, which means we will render it conditionally based on the `previous` prop.
```

2020-12-10 15:10 UTC, Trancever approved these changes

2020-12-14 10:08 UTC, lukewalczak requested changes

2020-12-14 10:08 UTC, lukewalczak commented on docs/pages/9.react-navigation.md
> +First, let's pass navigation props to `CustomNavigationBar`:
```suggestion
Firstly, pass navigation props to `CustomNavigationBar`:
```

2020-12-14 10:08 UTC, lukewalczak commented on docs/pages/9.react-navigation.md
> +As a second step, we check if navigation has previous state. If it has, it means there is another screen on the stack beneath the current screen and we should render the back arrow button in such a c
```suggestion
Secondly, check if navigation has previous state. If it has, it means there is another screen on the stack beneath the current screen and we should render the back arrow button in such a case.
```

2020-12-14 10:08 UTC, lukewalczak commented on docs/pages/9.react-navigation.md
> +Another interesting pattern that can be implemented with React-Native-Paper and React-Navigation is a "hamburger menu". Thanks to the Menu component we can add a nice looking pop-up to our Appbar. To
```suggestion
Another interesting pattern that can be implemented with `react-native-paper` and `react-navigation` is a "hamburger menu". Thanks to the `Menu` component we can add a nice looking pop-up to our `Appbar`. To implement this feature we need to make a couple of changes in `CustomNavigationBar`:
```

2020-12-14 10:51 UTC, lukewalczak approved these changes

2020-12-14 11:39 UTC, merged