fix: make text non selectable if inside a button
callstack/react-native-paper pull request #2283
Opened 2020-10-10 18:43 UTC by RichardLindhout

### Summary
Fixes: https://github.com/callstack/react-native-paper/issues/2258
![94059145-50e76680-fde2-11ea-82d9-8c01f65f6415](https://user-images.githubusercontent.com/6492229/95662697-22cf8980-0b39-11eb-9a51-291d85354459.gif)

### Test plan

2020-10-20 08:55 UTC, satya164 approved these changes

2020-10-27 09:40 UTC, Trancever commented
@RichardLindhout Thanks for the contributions! Could you resolve the conflicts and make sure lint and tests are passing? Once it's done we would like to merge the PR.

2020-10-28 21:54 UTC, RichardLindhout commented
Yes, will try to look at it this week a little bit short on time a.t.m.

2020-10-30 12:37 UTC, RichardLindhout commented
@Trancever done

2020-10-30 20:15 UTC, RichardLindhout commented
@Trancever We still need it inside the react-native-vector package but I don't think the maintainer will add this anytime soon based on all the PR's which are open.

I'll add it here too!

2020-11-03 15:16 UTC, Trancever requested changes

2020-11-03 15:16 UTC, Trancever commented on flow-typed/npm/babel-preset-react-native_vx.x.x.js
> -  declare module.exports: $Exports<'babel-preset-react-native/lib/resolvePlugins'>;
Why did you make all these changes in flow-types directory? You must have run prettier on it by mistake.

Btw, I don't think we need flow type definitions anymore, but let's remove it in separate PR.

2020-11-03 15:16 UTC, Trancever commented on flow-typed/npm/babel-preset-react-native_vx.x.x.js
> -  declare module.exports: $Exports<'babel-preset-react-native/lib/resolvePlugins'>;
Please revert all not related changes if possible 🙏

2020-11-03 15:16 UTC, Trancever commented on package.json
> +    "prettier": "./node_modules/.bin/prettier --write './src/**/*.{tsx,ts,js,css,html}'"
I don't think we need that script, it should be handled by the code editor with on save action.

Anyway, It should run the prettier on src and example directories only and if we really want that then let's do it in a separate PR, please.

2020-11-03 15:36 UTC, RichardLindhout commented on flow-typed/npm/babel-preset-react-native_vx.x.x.js
> -  declare module.exports: $Exports<'babel-preset-react-native/lib/resolvePlugins'>;
Will do, did indeed run prettier outside of the src

2020-11-17 10:20 UTC, Trancever commented
@RichardLindhout What's the status of it? Let me know if you don't have time to work on this one so someone from the core team will finish it. Cheers!

2020-11-18 21:06 UTC, RichardLindhout commented
Thanks for the feedback! It would be nice if the core-team could cherry-picking the commits since I had a hard time to fix this the last time since I don't 'get' how that works

2020-12-02 21:45 UTC, RichardLindhout commented
Hey @Trancever I have fixed some new conflicts, could we maybe merge this soon?

2020-12-08 09:37 UTC, Trancever commented
@RichardLindhout I cherry-picked only the relevant commit and it's already on a master!

2020-12-08 09:37 UTC, closed without merging