fix: paddingHorizontal with TextInput.Affix
callstack/react-native-paper pull request #2312
Opened 2020-10-23 14:26 UTC by dcangulo

### Summary
Fixes: #2303 

`paddingHorizontal` is disregarded when using `left` prop on `TextInput`.

### Test plan
**Sample Code in screenshot:**
```js
import React from 'react';
import { SafeAreaView, View } from 'react-native';
import { TextInput } from 'react-native-paper';

export default function App() {
  const [text, setText] = React.useState('');

  return (
    <SafeAreaView>
      <View style={{ padding: 20 }}>
        <TextInput
          label='Contact Number'
          value={text}
          onChangeText={setText}
          left={<TextInput.Affix text='+63' />}
          style={{ paddingHorizontal: 60 }}
        />
      </View>
    </SafeAreaView>
  );
}
```

**Before this PR:**
<img width="357" alt="Screen Shot 2020-10-23 at 10 08 14 PM" src="https://user-images.githubusercontent.com/36528176/97015554-499caf80-157e-11eb-8690-0de84c109753.png">

**After this PR:**
<img width="373" alt="Screen Shot 2020-10-23 at 10 17 53 PM" src="https://user-images.githubusercontent.com/36528176/97015648-646f2400-157e-11eb-808d-e30b6c0feba1.png">

2020-10-23 15:54 UTC, dcangulo commented
@Trancever @unikvozm @jbinda @matkoson @OlimpiaZurek Please check. Thanks.

2020-10-26 11:27 UTC, Trancever requested changes

2020-10-26 11:27 UTC, Trancever commented on src/components/TextInput/Adornment/Affix.tsx
> +  paddingHorizontal?: string | number | undefined;
Can we type it as `paddingHorizontal?: number;`?

2020-10-26 11:27 UTC, Trancever commented on src/components/TextInput/Adornment/Affix.tsx
> +    paddingHorizontal !== undefined && typeof paddingHorizontal === 'number'
If we change the type we won't need this check `typeof paddingHorizontal === 'number'`

2020-10-26 11:27 UTC, Trancever commented on src/components/TextInput/Adornment/TextInputAdornment.tsx
> +  paddingHorizontal?: string | number | undefined;
Same here

2020-10-26 11:27 UTC, Trancever commented on src/components/TextInput/Adornment/TextInputAdornment.tsx
> +  paddingHorizontal?: string | number | undefined;
And here

2020-10-26 12:58 UTC, dcangulo commented on src/components/TextInput/Adornment/Affix.tsx
> +  paddingHorizontal?: string | number | undefined;
@Trancever 

I'm not sure but I get `Type 'string | number | undefined' is not assignable to type 'number'.` error if I use `paddingHorizontal?: number;`. I am also new to typescript, any pointers will be appreciated.

Also according to the [docs](https://reactnative.dev/docs/layout-props#paddinghorizontal), `paddingHorizontal` has a type of `number, string`.

2020-10-27 09:38 UTC, Trancever commented on src/components/TextInput/Adornment/Affix.tsx
> +  paddingHorizontal?: string | number | undefined;
Ok, I see. Then it should be `paddingHorizontal?: number | string`. We don't have to add `undefined`, because we already have a question mark after the prop name.

2020-10-27 10:20 UTC, dcangulo commented
@Trancever Updated to `paddingHorizontal?: number | string`. Please check. Thanks.

2020-12-08 10:28 UTC, Trancever commented
Merged in https://github.com/callstack/react-native-paper/commit/4b1c150d26f1756b5e1d856322faec5d3da5885e

2020-12-08 10:28 UTC, closed without merging

2023-05-05 08:52 UTC, ecmap commented
Does TextInput.Icon support?