fix: add support for textAlign
callstack/react-native-paper pull request #2369
Opened 2020-11-20 20:10 UTC by RichardLindhout

### Summary
https://github.com/callstack/react-native-paper/issues/2185

### Test plan
Test on iOS, Android, web

2020-11-23 09:13 UTC, Trancever requested changes

2020-11-23 09:13 UTC, Trancever commented on .expo/settings.json
> +  "dev": true,
Could you remove that file from the PR?

2020-11-23 16:12 UTC, RichardLindhout commented on .expo/settings.json
> +  "dev": true,
Yes will do, will also add it in the .gitignore so it won't be added for other people too

2020-12-01 12:51 UTC, Trancever approved these changes

2020-12-01 12:51 UTC, merged