[wip] feat: add navigation to first and last page
callstack/react-native-paper pull request #2455
Opened 2020-12-20 13:02 UTC by unikvozm

### Summary
#2416

- [x] add navigation to first and last page
- [ ] fix bug with text displaying the last row
- [ ] add select for number of rows

### Test plan

2021-01-05 12:36 UTC, Trancever commented
Hey @unikvozm Is this PR ready for review? Could you please make a nice looking screenshot of the component and update the one we currently display in the documentation for DataTable.Pagination component?

2021-01-05 12:43 UTC, unikvozm commented
> Hey @unikvozm Is this PR ready for review? Could you please make a nice looking screenshot of the component and update the one we currently display in the documentation for DataTable.Pagination component?

Hi @Trancever, unfortunately, I haven't got enough time to finish it =( only 1/3 of this is finished. Will try to get it ready this week.

2021-01-05 13:24 UTC, Trancever commented
@unikvozm No worries! All good, take your time :) just wanted to check the status.

2021-01-10 14:58 UTC, unikvozm commented
@Trancever, could you suggest me how to change the screenshot in the documentation, please?

2021-02-25 14:56 UTC, Angelk90 commented
@unikvozm , @Trancever : Are there any news?

2021-04-16 12:00 UTC, Angelk90 commented
@Trancever : Are there any news?

2021-04-16 12:53 UTC, satya164 requested changes

2021-04-16 12:53 UTC, satya164 commented on example/src/Examples/DataTableExample.tsx
> +            setItemsPerPage={setItemsPerPage}
Change this prop to `onItemsPerPageChange` or something like that

2021-04-16 12:53 UTC, satya164 commented on example/src/Examples/DataTableExample.tsx
> +            showFastPagination
It's not clear from the prop name on what this does

2021-04-19 09:59 UTC, Angelk90 commented
@unikvozm , @Trancever : Are there any news?

2021-04-20 09:34 UTC, lukewalczak commented
***UPDATES***

1. We've decided to not hide the pagination dropdown on smaller device, instead we're wrapping them into two lines.

2. Props are renamed, most of them are new, however existing one `label` was renamed to `selectPageDropdownLabel`, so it should be consider as a breaking change.

***SCREENSHOTS***

<details>
<summary>iPhone 8</summary>

portrait | landscape
--- | ---
<img width="496" alt="Zrzut ekranu 2021-04-20 o 09 44 57" src="https://user-images.githubusercontent.com/22746080/115371599-6848cf80-a1ca-11eb-826b-e246f8a1de76.png"> | <img width="857" alt="Zrzut ekranu 2021-04-20 o 09 45 01" src="https://user-images.githubusercontent.com/22746080/115371614-6b43c000-a1ca-11eb-8861-893e5b616401.png">

</details>

<details>
<summary>iPad</summary>

<img width="663" alt="Zrzut ekranu 2021-04-20 o 09 55 21" src="https://user-images.githubusercontent.com/22746080/115373424-27ea5100-a1cc-11eb-906a-72d911a76ff6.png">

</details>

<details>
<summary>Android</summary>

portrait | landscape
--- | ---
<img width="404" alt="Zrzut ekranu 2021-04-20 o 09 47 40" src="https://user-images.githubusercontent.com/22746080/115373543-47817980-a1cc-11eb-93ed-32f9cba8f240.png"> | <img width="784" alt="Zrzut ekranu 2021-04-20 o 09 47 49" src="https://user-images.githubusercontent.com/22746080/115373550-494b3d00-a1cc-11eb-9abe-6fbc26a7f78a.png">


</details>

<details>
<summary>web</summary>

<img width="501" alt="Zrzut ekranu 2021-04-20 o 09 45 37" src="https://user-images.githubusercontent.com/22746080/115373608-5536ff00-a1cc-11eb-947a-f001026908be.png">

</details>

2021-04-20 09:35 UTC, lukewalczak commented on example/src/Examples/DataTableExample.tsx
> +            setItemsPerPage={setItemsPerPage}
Done.

2021-04-20 09:35 UTC, lukewalczak commented on example/src/Examples/DataTableExample.tsx
> +            showFastPagination
Renamed.

2021-05-11 20:01 UTC, Angelk90 commented
@unikvozm , @Trancever, @lukewalczak : Are there any news?

2021-05-21 12:51 UTC, brunohkbx commented
Sure, will do!

2021-05-23 16:23 UTC, dsznajder commented on src/components/DataTable/DataTablePagination.tsx
> +                    icon={'menu-down'}
```suggestion
                    icon="menu-down"
```

2021-05-24 12:24 UTC, brunohkbx commented on src/components/DataTable/DataTable.tsx
> + * const optionsPerPage = [2, 3, 4];
hey @lukewalczak can we also update this img `<img src="screenshots/data-table.png" />` ?. It looks so small on desktop
![Screenshot from 2021-05-24 09-08-30](https://user-images.githubusercontent.com/6487206/119345806-c3f5f500-bc6f-11eb-819c-4a066eb31094.png)

2021-05-24 12:24 UTC, brunohkbx commented on src/components/DataTable/DataTablePagination.tsx
> +    <View
Accessibility wise I found this issue on android: 
![bug](https://user-images.githubusercontent.com/6487206/119346266-5f876580-bc70-11eb-8b07-b6f8d38a0463.jpeg)

It focus on the whole card when I tried to focus on the row `Rows per page`

2021-05-24 12:24 UTC, brunohkbx commented on src/components/DataTable/DataTablePagination.tsx
> +            <View
I think you can have just a single `View` here moving the style `style={styles.nonIconsContainer}` to this one

2021-05-25 08:01 UTC, lukewalczak commented on src/components/DataTable/DataTablePagination.tsx
> +    <View
I think it's not related to DataTable component itself. I guess `Card` is blocking the access to the nested components in terms of a11y in the example - passing `<Card accessible={false} ...` can solve the issue.

2021-05-25 08:02 UTC, lukewalczak commented on src/components/DataTable/DataTable.tsx
> + * const optionsPerPage = [2, 3, 4];
Sure

2021-05-25 08:05 UTC, lukewalczak commented on src/components/DataTable/DataTablePagination.tsx
> +            <View
Correct. Looks like I forgot to do that after moving `label` out of that `View`

2021-05-26 11:58 UTC, dsznajder approved these changes

2021-05-27 10:19 UTC, brunohkbx approved these changes
Looks good!

2021-05-27 15:08 UTC, merged

2021-08-11 05:13 UTC, sugata98 commented
The pagination control buttons remain black in dark mode, thus not visible. I am unable to fix this using theme prop. Any help?

2021-08-11 08:22 UTC, Angelk90 commented
@sugata98 : Try posting a screenshot and sample code so they will be more helpful in understanding what the problem is and how to fix it.

2021-08-11 08:52 UTC, sugata98 commented
`<DataTable.Pagination
                page={page}
                numberOfPages={Math.ceil(sortedItems.length / itemsPerPage)}
                onPageChange={page => setPage(page)}
                label={`${from + 1}-${to} of ${sortedItems.length}`}
                numberOfItemsPerPageList={numberOfItemsPerPageList}
                numberOfItemsPerPage={itemsPerPage}
                onItemsPerPageChange={onItemsPerPageChange}
                showFastPaginationControls
                selectPageDropdownLabel={'Rows per page'}
               theme={{
                  dark: theme.mode == 'light' ? false : true,
                  colors: {
                    text: theme.PRIMARY_TEXT_100,
                    primary: 'red',
                  },
                }}
              />`
BY using the theme prop I was able to change the text color to white in dark mode, but the dropdown and the pagination controls at the button remains white and dark respectively even if I change theme to dark.
![WhatsApp Image 2021-08-11 at 2 17 30 PM](https://user-images.githubusercontent.com/20355754/128999189-8b4a628a-df96-44a1-927d-d2be33910113.jpeg)

![WhatsApp Image 2021-08-11 at 2 17 30 PM (1)](https://user-images.githubusercontent.com/20355754/128999209-61888020-a1d4-4dcb-ae52-48887981f303.jpeg)