feat: add disableSafeAreaInsets prop in Modal
callstack/react-native-paper pull request #2474
Opened 2020-12-31 23:36 UTC by ahce

### Motivation

This prop is necessary when you need to see content in full screen on iPhone X/11

### Test plan
1. Download this branch
2. Open Modal example
3. Change the prop disableSafeAreaInsets (iPhone X/11)

### Actual behaviour
![image](https://user-images.githubusercontent.com/12452003/79098271-a0a00d00-7d2f-11ea-8fb2-7e91b3ca3808.png)

### Behaviour with  disableSafeAreaInsets set to true
![image](https://user-images.githubusercontent.com/12452003/79098267-9bdb5900-7d2f-11ea-963d-b6647ae4e15e.png)

2021-01-05 09:32 UTC, Trancever requested changes

2021-01-05 09:32 UTC, Trancever commented on src/components/Modal.tsx
> +   * Determine whether the insets are applied.
```suggestion
   * Determines whether the insets are applied.
```

2021-01-05 09:53 UTC, Trancever requested changes

2021-01-05 09:53 UTC, Trancever commented on src/components/Modal.tsx
> +  disableSafeAreaInsets?: boolean;
We would prefer to have `safeAreaInsets` prop instead where users could pass `top` and `bottom` properties to override the default behavior. Could you change the implementation, please?

2021-01-05 13:43 UTC, ahce-meli commented on src/components/Modal.tsx
> +  disableSafeAreaInsets?: boolean;
@Trancever you think is better pass a wrapperStyle?

2021-01-05 13:45 UTC, ahce commented on src/components/Modal.tsx
> +  disableSafeAreaInsets?: boolean;
you think is better pass a wrapperStyle?

2021-01-05 14:30 UTC, Trancever commented on src/components/Modal.tsx
> +  disableSafeAreaInsets?: boolean;
Yes, we can even call it simply `style` :) Please provide a nice description for this prop so it's clear what can be achieved using it. Thanks!

2021-01-06 16:08 UTC, ahce commented on src/components/Modal.tsx
> +  disableSafeAreaInsets?: boolean;
done!

2021-01-08 08:07 UTC, Trancever approved these changes

2021-01-08 08:08 UTC, merged