feat: add outlineColor prop in TextInputOutlined
callstack/react-native-paper pull request #2475
Opened 2020-12-31 23:53 UTC by ahce

### Motivation

Allows to controls the outline color.

### Test plan

1. Download this branch
2. Open the TextInput example
3. Change the prop outlineColor

### Demo
```js
import React, { Fragment } from 'react';
import { TextInput } from 'react-native-paper';

const Demo = () => (
  <Fragment>
    <TextInput mode='outlined' />
    <TextInput mode='outlined' outlineColor='red' />
    <TextInput mode='outlined' outlineColor='blue' />
    <TextInput mode='outlined' outlineColor='green' />
  </Fragment>
);
```

![image](https://user-images.githubusercontent.com/12452003/103431128-1c860200-4baa-11eb-95db-e1ec2e5a6c3c.png)

2021-04-29 17:43 UTC, ahce commented
@Trancever any chance to merge this?

2021-04-29 19:32 UTC, lukewalczak commented
I'm not convinced in introducing the additional prop since you can customize the active/inactive color by passing the specific one via theme prop, e.g.:

```
     <TextInput
        mode="outlined"
        theme={{ colors: { 
          primary: 'green', // active outline color
          placeholder: 'purple' // inactive outline color
          } 
        }}
        ...
     />
 ```

2021-05-01 07:19 UTC, ahce commented
> I'm not convinced in introducing the additional prop since you can customize the active/inactive color by passing the specific one via theme prop, e.g.:
> 
> ```
>      <TextInput
>         mode="outlined"
>         theme={{ colors: { 
>           primary: 'green', // active outline color
>           placeholder: 'purple' // inactive outline color
>           } 
>         }}
>         ...
>      />
> ```

Hi @lukewalczak, thanks for your reply!

With theme also changes placeholder and label color, check this [demo](https://snack.expo.io/@ahce/rn-textinput-example) 

My PR has the same behavior as [underlineColor](https://github.com/callstack/react-native-paper/blob/main/src/components/TextInput/TextInput.tsx#L62) prop

2021-05-05 12:40 UTC, lukewalczak commented on src/components/TextInput/TextInputOutlined.tsx
> +            outlineColor={outlineColor || defaultOutlineColor}
Actually with that condition there won't be any difference between disabled and enabled state, since `outlineColor` will be always defined if passed by user.

### Current behavior

enabled | disabled
--- | ---
<img width="495" alt="Zrzut ekranu 2021-05-5 o 14 33 54" src="https://user-images.githubusercontent.com/22746080/117141627-0df56480-adaf-11eb-9095-9525b6f34ff0.png"> |<img width="495" alt="Zrzut ekranu 2021-05-5 o 14 34 02" src="https://user-images.githubusercontent.com/22746080/117141631-0f269180-adaf-11eb-8714-12164c9a4dc2.png">


### `outlineColor` prop passed

enabled | disabled
--- | ---
<img width="495" alt="Zrzut ekranu 2021-05-5 o 14 36 39" src="https://user-images.githubusercontent.com/22746080/117141899-6298df80-adaf-11eb-91d9-c2e20a7be9d6.png"> |<img width="495" alt="Zrzut ekranu 2021-05-5 o 14 36 39" src="https://user-images.githubusercontent.com/22746080/117141919-6af11a80-adaf-11eb-8a0e-88d681403753.png">


Please correct it to have the visual feedback between those two states.

2021-05-05 12:40 UTC, lukewalczak requested changes
Left one issue which has to be solved before merge.

2021-05-05 12:42 UTC, lukewalczak commented
> Hi @lukewalczak, thanks for your reply!

@ahce thanks for specifying more details! I see the reason for that PR and would like to merge, however there is one issue, which has to be fixed before.

2021-05-05 23:52 UTC, ahce commented on src/components/TextInput/TextInputOutlined.tsx
> +            outlineColor={outlineColor || defaultOutlineColor}
Done!

2021-05-06 09:53 UTC, lukewalczak requested changes

2021-05-06 09:53 UTC, lukewalczak commented on src/components/TextInput/TextInputOutlined.tsx
> +        outlineColor === 'transparent' ? outlineColor : colors.disabled;
I guess the reason for that check is to have transparent outline when input is disabled, but the way you handle it is incorrect. User can specify the color in various ways using hex or rgb format as well. To check if the passed outlineColor is transparent, please introduce the variable:

`const isTransparent = color(customOutlineColor).alpha() === 0`

then:

`outlineColor = isTransparent ? customOutlineColor : placeholderColor;`

2021-05-06 09:53 UTC, lukewalczak commented on src/components/TextInput/TextInputOutlined.tsx
> +      outlineColor,
```suggestion
      outlineColor: customOutlineColor,
```

2021-05-06 09:53 UTC, lukewalczak commented on src/components/TextInput/TextInputOutlined.tsx
> +      customOutlineColor,
```suggestion
      outlineColor,
```

2021-05-06 09:53 UTC, lukewalczak commented on src/components/TextInput/TextInputOutlined.tsx
> +      customOutlineColor = outlineColor || colors.placeholder;
```suggestion
      outlineColor = customOutlineColor || placeholderColor;
```

2021-05-06 09:53 UTC, lukewalczak commented on src/components/TextInput/TextInputOutlined.tsx
> +            outlineColor={customOutlineColor}
```suggestion
            outlineColor={outlineColor}
```

2021-05-06 17:39 UTC, ahce commented on src/components/TextInput/TextInputOutlined.tsx
> +      outlineColor,
Done!

2021-05-06 17:39 UTC, ahce commented on src/components/TextInput/TextInputOutlined.tsx
> +      customOutlineColor,
Done!

2021-05-06 17:39 UTC, ahce commented on src/components/TextInput/TextInputOutlined.tsx
> +            outlineColor={customOutlineColor}
Done!

2021-05-27 14:58 UTC, lukewalczak approved these changes

2021-05-27 15:02 UTC, merged