feat: add prop right to DrawerItem
callstack/react-native-paper pull request #2505
Opened 2021-01-14 03:27 UTC by brunohkbx

### Summary
It would be nice to be able to render a badge or chip in the Drawer.Item

### Test plan
1. Open the example app and see the Drawer.Item using a badge

![example](https://user-images.githubusercontent.com/6487206/104540868-23c3fb80-55ff-11eb-9a47-f3935de1040f.jpeg)

2021-01-14 03:32 UTC, brunohkbx commented on src/components/Drawer/DrawerItem.tsx
> +  right?: () => React.ReactNode;
@Trancever I think it should be just a `React.ReactNode` but I used a callback since most components are following this pattern.

2021-04-14 08:12 UTC, Trancever requested changes

2021-04-14 08:12 UTC, Trancever commented on src/components/Drawer/DrawerItem.tsx
> +  right?: () => React.ReactNode;
@brunohkbx Can we change the type to `right?: (props: { color: string }) => React.ReactNode;` ? I think it makes sense to passDrawer's content color here, so users can apply it to the right element if they want.

2021-04-14 12:42 UTC, brunohkbx commented
Done @Trancever :+1: I updated the example as well

2021-05-12 15:39 UTC, lukewalczak approved these changes
@brunohkbx really nice and useful enhancement, thanks!

2021-05-12 17:41 UTC, merged