feat: add card mode outlined
callstack/react-native-paper pull request #2512
Opened 2021-01-19 02:48 UTC by brunohkbx

### Summary
Implement MD outlined card.

https://material.io/components/cards

### Test plan
1. Open the example app
2. Check the example showing an outlined card

![outlined-card](https://user-images.githubusercontent.com/6487206/104981483-76c6f580-59e7-11eb-8d9c-841f4d16ff10.jpeg)

2021-01-19 13:22 UTC, Trancever requested changes

2021-01-19 13:22 UTC, Trancever commented on src/components/Card/Card.tsx
> +  mode?: 'elevated' | 'outlined';
I don't like the way it's typed currently. The outlined card shouldn't accept elevation prop. Could you try something like that:

```js
type OutlinedCardProps = {
  mode?: 'outlined';
  elevation: never;
};

type ElevatedCardProps = {
  mode?: 'elevated';
  elevation?: number;
};

type Props = (OutlinedCardProps | ElevatedCardProps) & { Common Props };
```

I haven't tried that, so it might not work, but I would like to explore this way of handling conditional types.

2021-01-19 13:22 UTC, Trancever commented on src/components/Card/Card.tsx
> +  mode?: 'elevated' | 'outlined';
I haven't tried that, so it might not work, but I would like to explore this way of handling conditional types.

2021-01-20 01:46 UTC, brunohkbx commented on src/components/Card/Card.tsx
> +  mode?: 'elevated' | 'outlined';
@Trancever I tried your approach and it wasn't working at first. So after some time debugging, I found a problem in the HOC `withTheme`. I removed it and it worked as follow:

Raises error
`<Card mode="outlined" elevation={3} />`

Works
`<Card mode="elevated" elevation={3} />`

After looking up the issue in `withTheme` I found a problem in its type declaration [here](https://github.com/callstack/react-theme-provider/blob/master/typings/index.d.ts#L12)
`$Without` it's not working as expected because `Pick` doesn't distribute over discriminated union types and you can read more about [here](https://github.com/microsoft/TypeScript/issues/28791)

Should we fix the type declaration first?
`type $Without<T, K extends keyof any> = T extends any ? Pick<T, Exclude<keyof T, K>> : never;` 
works for me

2021-01-22 10:11 UTC, Trancever commented on src/components/Card/Card.tsx
> +  mode?: 'elevated' | 'outlined';
I think we should first fix the type of the withTheme HOC. Could you submit a PR? 🙏

2021-01-23 02:26 UTC, brunohkbx commented on src/components/Card/Card.tsx
> +  mode?: 'elevated' | 'outlined';
Done :+1: https://github.com/callstack/react-theme-provider/pull/96

2021-04-13 10:07 UTC, lukewalczak commented on src/components/Card/Card.tsx
> +    borderColor: 'rgba(0, 0, 0, 0.12)',
I guess that `borderColor` should depend on the theme and it should be specified in that way:

```
  const borderColor = color(theme.dark ? white : black)
    .alpha(0.12)
    .rgb()
    .string();
```

However, I didn't check the specification, so please look on it.

2021-04-13 11:39 UTC, lukewalczak commented on example/src/Examples/CardExample.tsx
>      </ScrollView>
Can we add one more example with media and buttons?

2021-04-23 03:02 UTC, brunohkbx commented
@lukewalczak I added a switch at the top to toggle the mode. WDTY?

2021-04-23 09:11 UTC, lukewalczak commented
Hey @brunohkbx, thanks for updating the PR! I like the idea of switch and the whole feature 🎉 . I will test it a bit, ping the theme provider lib one more time and go through the code. Anyway I guess we're close to ship it!

2021-05-06 11:12 UTC, souhe commented
@brunohkbx I just published a new version of theme-provider with your fix. Sorry for the lag. 
The new version is now `v3.0.6` I had to bump it a lot since we did a mistake with the previous release ;)

2021-05-06 12:28 UTC, brunohkbx commented
@souhe thanks. I will update this PR

2021-05-12 17:53 UTC, brunohkbx commented
TS now complains when using mode `outlined` + elevation cc @Trancever @lukewalczak 
![Screenshot from 2021-05-12 14-51-14](https://user-images.githubusercontent.com/6487206/118021570-c4b68f00-b331-11eb-9b57-9b88bcd6e002.png)

2021-05-12 18:29 UTC, lukewalczak commented
> TS now complains when using mode outlined + elevation

Isn't a correct behavior since you typed:

```
type OutlinedCardProps = {
  mode: 'outlined';
  elevation: never;
};
```

2021-05-12 18:38 UTC, brunohkbx commented
@lukewalczak yeah it is. I'm just showing it. Works now with `callstack/react-theme-provider` 3.0.6

2021-05-12 18:42 UTC, lukewalczak commented
> yeah it is. I'm just showing it. Works now with callstack/react-theme-provider 3.0.6

Ahhh ok I see, sorry for misunderstanding 😅 thanks @brunohkbx!

2021-05-14 19:11 UTC, lukewalczak approved these changes

2021-05-14 19:11 UTC, lukewalczak commented
Awesome feature, thanks @brunohkbx for your work!

2021-05-14 19:12 UTC, merged