fix: upgrade ts types to latest version
callstack/react-native-paper pull request #2522
Opened 2021-01-25 08:39 UTC by Trancever

### Summary

This PR upgrades react native types to v0.63 and fixes few eslint warnings.

### Test plan

Reinstall node_modules and run `yarn typescript`

2021-01-25 09:01 UTC, satya164 requested changes

2021-01-25 09:01 UTC, satya164 commented on src/components/Appbar/Appbar.tsx
> +        : // @ts-ignore
Why is this needed? Can `backgroundColor` be non-string? Then we should check if it's a string first. (Same in other files)

2021-01-25 09:01 UTC, satya164 commented on src/components/BottomNavigation.tsx
> +                // @ts-ignore
Add a comment too

2021-01-25 14:45 UTC, Trancever commented on src/components/ActivityIndicator.tsx
> +    overflow: 'hidden' as ViewStyle['overflow'],
👍

2021-01-27 01:59 UTC, maltoze commented on src/components/Appbar/Appbar.tsx
> +        : // @ts-ignore
Colors simply are no longer just strings in v0.63.

2021-02-02 06:43 UTC, imnotjames commented on src/components/Button.tsx
>          accessibilityComponentType="button"
I think `accessibilityComponentType` also needs to be ignored - unless I'm misunderstanding how `// @ts-ignore` works

2021-02-12 09:20 UTC, chybisov commented
Do you guys have any plans to merge this? It's very annoying to see types errors 😄

2021-02-17 14:43 UTC, fr-animal commented
LGTM!

2021-02-21 22:33 UTC, merged