Update searchbar props
callstack/react-native-paper pull request #2564
Opened 2021-02-25 03:30 UTC by bmburlingame

onFocus and onBlur are valid props for the searchbar

### Summary

### Test plan

2021-03-01 12:35 UTC, wojteg1337 requested changes

2021-03-01 12:35 UTC, wojteg1337 commented on src/components/Searchbar.tsx
> +  onBlur?: (args: any) => void;
I think this is not a valid type for callback argument

2021-03-01 12:35 UTC, wojteg1337 commented on src/components/Searchbar.tsx
> +  onFocus?: (args: any) => void;
Callback type here is `NativeSyntheticEvent` of `TextInput`

2021-04-09 10:57 UTC, lukewalczak commented
Hey @bmburlingame I think there is no need to introduce these two props since `Searchbar` already inherits them from `TextInput` on which it's based.

2021-04-09 10:57 UTC, closed without merging