feat: add prop color to TextInputIcon
callstack/react-native-paper pull request #2661
Opened 2021-04-13 02:11 UTC by brunohkbx

### Summary
This PR adds a new prop `color` to the component `TextInputIcon`. It accepts whether a function or a string, making it easier to change the icon color when the input is focused as in the MD example below.

![Screenshot from 2021-04-12 23-09-41](https://user-images.githubusercontent.com/6487206/114486407-37720480-9be4-11eb-9e39-47b87c55fe16.png)

### Test plan
Check the example app

2021-04-13 08:41 UTC, lukewalczak commented on example/src/Examples/TextInputExample.tsx
> +              color={(focused) => (focused ? primary : 'black')}
I think we shouldn't use hardcoded color since it will not change when switching between themes. I would suggest to use as a fallback `text` color from theme, which is used as a [default](https://github.com/callstack/react-native-paper/blob/main/src/components/IconButton.tsx#L103) in `IconButton` or type that prop as a possibly `undefined` and then fallback to it.

2021-04-13 08:41 UTC, lukewalczak requested changes
Left one comment, except it lgtm. Thanks!

2021-04-13 12:44 UTC, brunohkbx commented
@lukewalczak thanks for reviewing it. I updated the type to `color?: ((isTextInputFocused: boolean) => string | undefined) | string;` and now is working fine to both light/dark themes.

2021-04-14 10:57 UTC, lukewalczak approved these changes

2021-04-20 11:12 UTC, merged