fix: typescript issue in banner when customizing buttons
callstack/react-native-paper pull request #2970
Opened 2021-11-08 02:34 UTC by ericledonge

### Summary

This PR fixing this issue: https://github.com/callstack/react-native-paper/issues/1670

With this fix, I can customize button you can pass other props that button component takes, without having TS crying, as described in the doc: https://callstack.github.io/react-native-paper/banner.html#actions

Maybe, the way I've submitted the modification in lib/typescript/components/Banner.d.ts is not good. I just want to change the line 32. I am new to both open source and typescript worlds. So let me know how to submit that correctly.

### Test plan

In my IDE, everything is ok:

<img width="1041" alt="Capture d’écran, le 2021-11-07 à 21 30 07" src="https://user-images.githubusercontent.com/6333396/140675105-092e8e1a-80e3-456f-92ca-4ddcc13afb32.png">

2021-11-30 15:29 UTC, Drakeoon requested changes
@ericledonge I think the way you also updated lib files here is fine. @lukewalczak any preferences about it?

I left a quick note, please apply it and I'll give a green light on this one. Imo a really good change 👍🏻

2021-11-30 15:29 UTC, Drakeoon commented on src/components/Banner.tsx
> +      onPress: () => void;
```suggestion
```

I think this line could be removed, since `onPress()` is already covered by `Button` interface

2021-11-30 15:34 UTC, Drakeoon commented
Oh, I actually thought we had the lib folder in our repo and it's just an update. I think you should also remove the lib changes, as we compile them for every release on our own @ericledonge

2021-12-09 15:24 UTC, ericledonge commented
@Drakeoon Oki, let me know if it's correct now.

2021-12-09 15:47 UTC, Drakeoon approved these changes
@lukewalczak looks good to me 👍🏻  Thanks @ericledonge

2021-12-10 09:13 UTC, merged