EventEmitter.removeListener('change', ...): Method has been deprecate…
callstack/react-native-paper pull request #3007
Opened 2021-12-12 16:14 UTC by pushpender-singh-ap

…d Issue Fixed

https://github.com/callstack/react-native-paper/issues/2984

### Summary

if (this.backHandlerSubscription?.remove) {
      this.backHandlerSubscription.remove();
    } else {
      BackHandler.removeEventListener('hardwareBackPress', this.handleDismiss);    <----   this event trigger when the user does not click on the menu option and the user press Hardware Back Button so no need to do this because BackHandler Listener is not subscribed.
    }

    if (this.dimensionsSubscription?.remove) {
      this.dimensionsSubscription.remove();
    } else {
      Dimensions.removeEventListener('change', this.handleDismiss);     <----   this event trigger when the user does not click on the menu option and the user press Hardware Back Button so no need to do this because BackHandler Listener is not subscribed.
    }

If you wanna see whole process recording click below links:
https://user-images.githubusercontent.com/73298854/145720046-2e3628d5-d94c-409d-9785-287d8432cd87.mp4

### Test plan

2021-12-12 21:10 UTC, lukewalczak commented on src/components/Menu/Menu.tsx
> +      this.handleDismiss;
We cannot handle that problem in that way since we are losing the backward compatibility.

I can suggest to rather revert your changes and create an `if statement` within `componentWillUnmount` and check whether `backHandlerSubscription` and `dimensionsSubscription` are defined:

```
 componentWillUnmount() {
    if (this.backHandlerSubscription && this.dimensionsSubscription) {
      this.removeListeners();
    }
  }
```

2021-12-12 21:10 UTC, lukewalczak requested changes
We cannot handle that problem in that way since we are losing the backward compatibility.

I can suggest to rather create an `if statement` within `componentWillUnmount` and check whether `backHandlerSubscription` and `dimensionsSubscription` are defined:

```
 componentWillUnmount() {
    if (this.backHandlerSubscription && this.dimensionsSubscription) {
      this.removeListeners();
    }
  }
```

2021-12-13 04:38 UTC, pushpender-singh-ap commented
@lukewalczak but why do we need this even we are not subscribing backhandler, but user clicks on the menu option private attachListeners trigger, and BackHandler Listeners are started Listening so in case we need to unsubscribe the Listeners.

If you see the video of the process when coming on the menu page and without touching the menu icon click on Hardware back to in case we don't need to unsubscribe the Backhandler (Because Backhandler Listener is not listening).

2021-12-13 10:12 UTC, lukewalczak commented
We are subscribing into the `BackHandler` and `Dimensions` within `attachListeners` when opening the `Menu` and accordingly we have to remove event listener when closing it e.g. by pressing android hardware back button.

In your case presented on the video, in fact, we are not subscribing to any of them, because `Menu` was not opened, that's why I'm suggesting to add the _if statement_ in `componentWillUnmount`.

Please consider the case when you've opened the `Menu` component, so you are subscribed to both listeners. When closing the component to remove listeners we need `BackHandler.removeEventListener(...)` and the same for `Dimensions` for the RN < 0.64.

2021-12-13 10:19 UTC, pushpender-singh-ap commented
ok, wait for this I will check in RN 0.63 version.

2021-12-13 11:06 UTC, pushpender-singh-ap commented
I make new repo with RN 0.63 version and install the same dep and change the same it's working fine.

we are not subscribing to any of them, because Menu was not opened and we are trying to remove listeners even we are not subscribed

For more information see this below video:

https://user-images.githubusercontent.com/73298854/145801430-e3c61522-f5cf-4132-b28c-2d4d0c05ba91.mp4

2021-12-13 12:15 UTC, lukewalczak commented
After deeper investigation my proposed solution cannot work on the previous RN, since both subscriptions will be undefined. It looks like I need to dive into listeners and make some refactor in all places where we are adding and removing them and create a separate PR for it.

2021-12-13 13:41 UTC, lukewalczak commented
@pushpender-singh-ap I will close it, because it's not the correct approach, however it solves the issue for you – I can suggest you to use patch-package library or base on fork, to keep that solution for you.
In the meantime I will work on more generic fix for all listeners and will let you know once it's ready.

Thanks for your effort and putting more light on that issue.

2021-12-13 13:41 UTC, closed without merging

2021-12-13 14:20 UTC, pushpender-singh-ap commented
check one time this commit is also working on  0.64+ & below 0.64 I tested on 0.63 & as well as 0.66.

Maybe this help you if you think that way it is better than the previous one inform me I will again generate PR.

https://github.com/pushpender-singh-ap/react-native-paper/commit/943d743272451840d25506372678c817f5e2ec81#diff-79e0d805785bbe8a0f585efebc274478388e7ce83323d87a7492930efd924de3

2021-12-13 14:21 UTC, pushpender-singh-ap commented
@lukewalczak  check one time this commit is also working on  0.64+ & below 0.64 I tested on 0.63 & as well as 0.66.

Maybe this help you if you think that way it is better than the previous one inform me I will again generate PR.

https://github.com/pushpender-singh-ap/react-native-paper/commit/943d743272451840d25506372678c817f5e2ec81#diff-79e0d805785bbe8a0f585efebc274478388e7ce83323d87a7492930efd924de3

2021-12-14 13:50 UTC, lukewalczak commented
Hello @pushpender-singh-ap, I'm looking for more generic fix solution for all listeners and already created initial solution. It's still WIP, since currently I'm checking whether I can make it even more generic. 
You can check the result on the [commit](https://github.com/callstack/react-native-paper/commit/1fb7d5e07c83af0c86fa64db039318b2867bcd06), maybe even install the library in your project from that branch and inform me if you're still observing any warnings.

2021-12-14 13:53 UTC, pushpender-singh-ap commented
@lukewalczak okk sure i will test this asap

2021-12-14 14:32 UTC, pushpender-singh-ap commented
@lukewalczak I am sharing with you the recording, I think the back handler removeEventListener not working if you see in the recording I use console.log for verification and logs return only first and last but not middle 2 logs.

https://user-images.githubusercontent.com/73298854/146017741-fabd84f7-eeb9-4624-b8d3-d2585ed3325e.mp4

2021-12-14 14:37 UTC, lukewalczak commented
Thanks for testing! I will check that in my free time, when will can work on it.

2021-12-14 14:40 UTC, pushpender-singh-ap commented
@lukewalczak no issue when you update something on this inform me I will test it.

2021-12-20 22:08 UTC, lukewalczak commented
Hey @pushpender-singh-ap, I think you were testing on the latest RN version and it's correct that you're not observing "inside" logs, since new `addEventListener` util works in the way where for:
* rn > 0.64 - return a subscription, so object with remove function is not going to be used
* rn < 0.63  - doesn't return subscription, so object is used and you should observe inside logs

2021-12-21 06:36 UTC, pushpender-singh-ap commented
@lukewalczak It's working fine in both versions.