feat: adjust button
callstack/react-native-paper pull request #3114
Opened 2022-03-08 20:28 UTC by lukewalczak

### Summary

### Test plan

2022-04-20 09:31 UTC, OlimpiaZurek approved these changes

2022-05-11 07:26 UTC, Drakeoon requested changes

2022-05-11 07:26 UTC, Drakeoon commented on src/components/Button/helpers.tsx
> +}: {
@lukewalczak Consider refactoring this function to use guard clauses. It would be more readable and maintainable. We could always asume to return `{
    backgroundColor,
    borderColor,
    textColor,
    borderWidth,
  };` and have getters for each variable put in a separate function

2022-05-11 11:10 UTC, lukewalczak commented on src/components/Button/helpers.tsx
> +}: {
Thanks @Drakeoon for pointing it out. When I started refactoring it I've noticed that we have to introduce two new props for background and text color separately. I will work on it right now.

2022-05-12 14:49 UTC, lukewalczak commented on src/components/Button/helpers.tsx
> +}: {
Done @Drakeoon!

2022-05-25 11:00 UTC, Drakeoon approved these changes

2022-05-27 10:23 UTC, merged