feat: add FAB size prop
callstack/react-native-paper pull request #3156
Opened 2022-04-18 14:04 UTC by joaoGabriel55

Feature asked from issue #3064

### Summary

Add a prop size at FAB component

### Test plan

Final result:

![image](https://user-images.githubusercontent.com/23138717/163819483-9b45386e-f7c9-43c2-8dff-1e049bd880d6.png)

2022-06-13 07:19 UTC, danieldanielecki commented
Much awaited change as per https://github.com/callstack/react-native-paper/pull/921

2022-06-15 21:21 UTC, lukewalczak commented
Hey @joaoGabriel55, due to renaming `next` branch (with Material You changes) to `main` there are conflicts. Could you please resolve it? If you'll need some help, please let me know.

2022-06-15 22:12 UTC, joaoGabriel55 commented
> Hey @joaoGabriel55, due to renaming `next` branch (with Material You changes) to `main` there are conflicts. Could you please resolve it? If you'll need some help, please let me know.

Yeah. I did rebase with the `main` branch, that is it?

2022-06-17 20:38 UTC, lukewalczak requested changes

2022-06-17 20:38 UTC, lukewalczak commented on src/components/FAB/FAB.tsx
> +   * Custom size for the `FAB`.
I would add a note that prop takes precedence over `size` prop.

2022-06-17 21:21 UTC, lukewalczak commented on src/components/FAB/FAB.tsx
> +   * Custom size for the `FAB`.
Please also add an annotation that prop is supported in v5:
`   * @supported Available in v5.x`

2022-06-27 15:17 UTC, merged