fix: correct changing Dialog backdrop color (#3259)
callstack/react-native-paper pull request #3260
Opened 2022-07-18 10:34 UTC by lukewalczak

### Summary

PR is adjusting changes included in the [PR](https://github.com/callstack/react-native-paper/pull/3259) to the `main` branch.

To override color backdrop color in `FAB.Group` the only way is to use `backdropColor` (supported on v4.x as well), since that color is different than typical backdrop used in `Modal` or `Dialog`.

At the same time, to the theme there was added `backdrop` color.

### Test plan

2022-08-02 08:42 UTC, slavikdenis requested changes

2022-08-02 08:42 UTC, slavikdenis commented on src/components/Modal.tsx
> +          testID={`${testID}-backdrop`}
Should we handle the case when `testID` is undefined?

2022-08-02 08:42 UTC, slavikdenis commented on src/components/Modal.tsx
> +  testID?: string;
Missing comment like so

```
  /**
   * testID to be used on tests.
   */
```

2022-08-03 11:19 UTC, lukewalczak commented on src/components/Modal.tsx
> +          testID={`${testID}-backdrop`}
Sure, there should be a default `testID`.

2022-08-03 12:36 UTC, slavikdenis approved these changes

2022-08-08 10:39 UTC, merged