New component: SegmentedButton
callstack/react-native-paper pull request #3283
Opened 2022-07-30 18:29 UTC by okwasniewski

This PR introduces new component named: `SegmentedButton`. 

### Summary

General overview of the component: https://m3.material.io/components/segmented-buttons/overview

Highlights:
- single or multi-selection
- segmented buttons can have 2-5 segments, segments cannot wrap into a new line
- icons can be used in place of labels
- icon next to the label is optional

### Test plan

Write tests for this component.

2022-08-03 13:59 UTC, satya164 requested changes

2022-08-03 13:59 UTC, satya164 commented on src/components/SegmentedButton/SegmentedButton.tsx
> +  onPress?: (value?: GestureResponderEvent | string) => void;
I think it's confusing that it can give `GestureResponderEvent` and `string`

2022-08-03 14:14 UTC, okwasniewski commented on src/components/SegmentedButton/SegmentedButton.tsx
> +  onPress?: (value?: GestureResponderEvent | string) => void;
You are right, I've removed the `string` type.

2022-08-06 09:58 UTC, Drakeoon commented on example/src/Examples/SegmentedButtonExample.tsx
> +      </List.Section>
@okwasniewski Consider creating separate components for individual examples. It would be a little easier to digest if someone wants to look at source

2022-08-07 15:33 UTC, okwasniewski commented on example/src/Examples/SegmentedButtonExample.tsx
> +      </List.Section>
Done ✅

2022-08-08 11:51 UTC, slavikdenis requested changes

2022-08-08 11:51 UTC, slavikdenis commented on src/components/SegmentedButton/SegmentedButton.tsx
> +  onPress?: (value?: GestureResponderEvent) => void;
`event?: GestureResponderEvent` would be more descriptive.
What do you think?

2022-08-08 11:51 UTC, slavikdenis commented on src/components/SegmentedButton/SegmentedButton.tsx
> +      ? context.value.includes(value || '')
I'm wondering if this would be worthy of wrapping with `useMemo` for a case where there would be a bunch of Segmented Buttons

2022-08-08 11:51 UTC, slavikdenis commented on src/components/SegmentedButton/SegmentedButton.tsx
> +  const paddingVertical = density
Shouldn't the condition here check for `isNumber(density)` instead of just truthy checking?

2022-08-08 12:01 UTC, okwasniewski commented on src/components/SegmentedButton/SegmentedButton.tsx
> +  const paddingVertical = density
Density has default value as `0` so i think it's safe to do it like so

2022-08-08 12:02 UTC, okwasniewski commented on src/components/SegmentedButton/SegmentedButton.tsx
> +  onPress?: (value?: GestureResponderEvent) => void;
You are right, I will fix it 👍🏻

2022-08-08 15:21 UTC, lukewalczak commented on src/components/SegmentedButton/SegmentedButton.tsx
> +const SegmentedButton = ({
Please add there a short component description and usage example, like you already did for `SegmentedButtonGroup`.

2022-08-08 15:26 UTC, lukewalczak commented on src/components/SegmentedButton/SegmentedButtonGroup.tsx
> + * ## Usage
Please adjust example usage similarly to the Appbar [example](https://callstack.github.io/react-native-paper/appbar.html) in the following way:

```
 ## Usage
 ### Single select
 ...
 ### Multiselect
 ```

2022-08-08 16:14 UTC, okwasniewski commented on src/components/SegmentedButton/SegmentedButton.tsx
> +      ? context.value.includes(value || '')
I'm not sure but I think it wouldn't give any performance improvements in our case. It would still re-run the compute function (in `useMemo`) on every re-render because of context as a dependency.

2022-08-12 12:11 UTC, lukewalczak commented on src/components/SegmentedButton/SegmentedButton.tsx
> +    <View style={[buttonStyle, [styles.button, style]]}>
```suggestion
    <View style={[buttonStyle, styles.button, style]}>
```

2022-08-12 16:00 UTC, satya164 requested changes
I'm not sure about the API of `SegementedButton` and `SegmentedButton.Group` given that `SegementedButton` cannot be used on its own similar to other components which have individual components as well as a group component.

It's more similar to the `FAB.Group` component. Probably it's better to have a single component that takes an array of items instead of having a group and children.

2022-08-12 16:04 UTC, okwasniewski commented on src/components/SegmentedButton/SegmentedButton.tsx
> +  label?: string;
You can use it only with icons

2022-08-13 08:15 UTC, okwasniewski commented on src/components/SegmentedButton/SegmentedButton.tsx
> +  onPress?: (event?: GestureResponderEvent) => void;
Yes, you don't need to pass `onPress` as checking functionality is handled by context.

2022-08-13 08:17 UTC, okwasniewski commented on src/components/SegmentedButton/SegmentedButton.tsx
> +  const borderRadius = (isV3 ? 5 : 1) * roundness;
There checks are copied directly from other components. For example: https://github.com/callstack/react-native-paper/blob/b027079eed9d15d71d5fc2aa2399e98c0ac83cfc/src/components/Button/Button.tsx#L232

2022-08-13 13:12 UTC, satya164 commented on src/components/SegmentedButton/SegmentedButton.tsx
> +  onPress?: (event?: GestureResponderEvent) => void;
I'm talking about the event parameter

2022-08-14 10:10 UTC, okwasniewski commented on src/components/SegmentedButton/SegmentedButtonGroup.tsx
> +  value: string | string[] | null;
None, fixed it 👍🏻

2022-08-14 11:06 UTC, okwasniewski commented on src/components/SegmentedButton/SegmentedButton.tsx
> +  segment?: 'first' | 'last';
This depends on index inside map: 
https://github.com/callstack/react-native-paper/blob/659fb6187c2c947bf50a101d0e8700a9b2a3fa61/src/components/SegmentedButton/SegmentedButtonGroup.tsx#L120-L121

I'm not sure how it should be set using context

2022-08-14 12:01 UTC, okwasniewski commented
@satya164 Thanks for your feedback 👍 I have a few questions about what to do next with this component.

> I'm not sure about the API of `SegementedButton` and `SegmentedButton.Group` given that `SegementedButton` cannot be used on its own similar to other components which have individual components as well as a group component.
> 
> It's more similar to the `FAB.Group` component. Probably it's better to have a single component that takes an array of items instead of having a group and children.

You are right, this component is not consistent with others (like `ToggleButton` and `ToggleButton.Group`). There are two options: allow it to be used without `SegmentedButton.Group` or refactor the API to pass array of items. 

First option is pretty straight forward just remove the context check. This approach maybe useful for people who want to customize and implement their own logic for handling the checked state.

Second approach would make the component easier to use, however less customizable - I'm not sure which one is better.

Regarding the second approach implementation: 
Should I just change the `Children.map` inside `SegmentedButton.Group` to map an array of passed items? Then rename the `SegmentedButton.Group` to a `SegmentedButton` and remove the current `SegmentedButton` export (to use it only internally) or how you would go about it?  

cc: @lukewalczak @Drakeoon - What do you guys think?

2022-08-15 19:07 UTC, lukewalczak commented
I can agree with @satya164, that we can change the `API` since `SegmentedButton` isn't an individual component.
Imo I would prefer the approach with removing the `SegmentedButton.Group` and `context` check rather than passing an array with items.

2022-08-16 07:55 UTC, okwasniewski commented
After internal discussion we decided to refactor the component API to pass the items array. Using the `SegmentedButton` component without group doesn't make sense. Current `SegmentedButton` export will be removed and used only internally and `SegmentedButton.Group` will be renamed to `SegmentedButtons`.

2022-08-22 11:21 UTC, lukewalczak approved these changes
Awesome work 🎉 Thanks for cooperation and adjusting comments to the feedback!

2022-08-23 06:20 UTC, satya164 requested changes

2022-08-23 06:20 UTC, satya164 commented on src/components/SegmentedButtons/SegmentedButtons.tsx
> +    density?: 0 | -1 | -2 | -3;
I think this option is a bit confusing. As a user, looking at the negative numbers doesn't tell me anything. MD docs sometimes have such confusing APIs. I'd avoid using magic numbers and use a union type of strings instead.

I'm not sure about the names, but for some other components, we have a prop like `compact` etc.

Another thing is that it probably doesn't make sense to provide different densities for each button, so I'd move this prop to the `SegmentedButtons` component itself.

2022-08-23 06:20 UTC, satya164 commented on src/components/SegmentedButtons/SegmentedButtons.tsx
> +export default withTheme(SegmentedButtons);
This should use `useTheme` hook instead.

Unrelated to this PR, but I see `useTheme` isn't getting `props.theme` in other places in the code - which makes the API inconsistent with components using `withTheme` that accept a `theme` prop to override `theme` locally. Should probably drop this feature altogether in next paper version or fix it for existing usage of `useTheme`.

2022-08-23 06:20 UTC, satya164 commented on src/components/__tests__/SegmentedButton.test.js
> +});
imo these tests are testing implementation details by checking for exact style properties. setting up some visual integration testing in the repo would be much better.

2022-08-23 06:20 UTC, satya164 commented on src/components/SegmentedButtons/SegmentedButtons.tsx
> +SegmentedButtons.displayName = 'SegmentedButtons';
This shouldn't be necessary. A component's name is automatically inferred from the function/class name. This is only needed in case the function is anonymous.

2022-08-23 06:20 UTC, satya164 commented on src/components/SegmentedButtons/SegmentedButtons.tsx
> +  }
Logging during render can result in a lot of duplicate warnings due to re-renders. Consider logging in an effect or using something like `warn-once` to show the warning only once.

Though I'm not sure such warning is needed here, considering we don't print such warnings anywhere else in the lib.

2022-08-23 06:20 UTC, satya164 commented on src/components/SegmentedButtons/SegmentedButtons.tsx
> + * @supported Available in v5.x
Seems unnecessary to repeat that it's available for 5.x when I'm reading the docs for 5.x.

2022-08-23 07:40 UTC, lukewalczak commented on src/components/SegmentedButtons/SegmentedButtons.tsx
> + * @supported Available in v5.x
I can agree, it's a kinda _misuse_, however, let's keep it for now. Maybe it's useful for someone who comparing v4 and v5 🤔 
Anyway, since that label is used also in the other two components, if we decide to remove it, I'll handle it in a separate PR.

2022-08-23 07:48 UTC, lukewalczak commented on src/components/SegmentedButtons/SegmentedButtons.tsx
> +  }
We have `console.warn` in 2-3 other places. From the perspective of a developer not so familiar with MD, it's worth showing the warning, but as you suggested, let's introduce and use `warn-once` _(will handle it in other places in the separate PR then)_.

2022-08-23 07:50 UTC, lukewalczak commented on src/components/SegmentedButtons/SegmentedButtons.tsx
> +export default withTheme(SegmentedButtons);
Noted. Will contact @Drakeoon , since he's working on theme refactor.

2022-08-23 07:58 UTC, lukewalczak commented on src/components/SegmentedButtons/SegmentedButtons.tsx
> +    density?: 0 | -1 | -2 | -3;
> I think this option is a bit confusing. As a user, looking at the negative numbers doesn't tell me anything. MD docs sometimes have such confusing APIs. I'd avoid using magic numbers and use a union type of strings instead.
> I'm not sure about the names, but for some other components, we have a prop like compact etc.

Maybe:

```
density?: 'regular' | 'small' | 'medium' | 'high'
```

> Another thing is that it probably doesn't make sense to provide different densities for each button, so I'd move this prop to the SegmentedButtons component itself.

Makes sense

2022-08-23 08:30 UTC, satya164 commented on src/components/SegmentedButtons/SegmentedButtons.tsx
> +  }
@lukewalczak the other logs for invalid usage, this is more like a guideline so not really the same thing

2022-08-23 17:39 UTC, okwasniewski commented on src/components/__tests__/SegmentedButton.test.js
> +});
This can be addressed in other PR

2022-08-23 17:42 UTC, okwasniewski commented on src/components/SegmentedButtons/SegmentedButtons.tsx
> +  }
You are right, I will remove this `console.warn` and the `warn-once` for other components can be addressed in separate PR

2022-08-23 17:44 UTC, okwasniewski commented on src/components/SegmentedButtons/SegmentedButtons.tsx
> +export default withTheme(SegmentedButtons);
I will change this to `useTheme()`

2022-08-23 18:00 UTC, okwasniewski commented on src/components/SegmentedButtons/SegmentedButtons.tsx
> + * @supported Available in v5.x
I will leave it for now, it can be addressed in separate PR.

2022-08-31 08:15 UTC, merged