fix: change RouteScreen visibility only on web
callstack/react-native-paper pull request #3346
Opened 2022-09-02 10:37 UTC by okwasniewski

### Summary

Adds display flex / none only on web. Fixes: #3292

### Test plan
CI test

2022-09-02 13:11 UTC, satya164 requested changes

2022-09-02 13:11 UTC, satya164 commented on src/components/__tests__/BottomNavigation.test.js
> +  Platform.OS = 'web';
Use `jest.spyOn(Platform, 'OS').mockImplementation(() => 'web')` and call `Platform.OS.mockRestore()` at the end of the file so that this doesn't affect other tests.

2022-09-02 13:11 UTC, satya164 commented on src/components/BottomNavigation/BottomNavigationRouteScreen.tsx
> +        style={[style, Platform.OS === 'web' && { display }]}
Let's add a comment explaining why it's done only for the Web.

2022-09-05 09:02 UTC, satya164 approved these changes

2022-09-05 09:11 UTC, lukewalczak approved these changes
Thanks @okwasniewski 🔥

2022-09-05 09:12 UTC, merged