chore: update eslint
callstack/react-native-paper pull request #3356
Opened 2022-09-06 09:12 UTC by jaworek

Eslint config of RN Paper is quite outdated. As a part of testing latest @callstack/eslint-config, I updated it.

### Summary

Update eslint config, eslint, and plugins that are used.

### Test plan

Pipelines pass and there are no regressions in functionality.

2022-09-07 14:03 UTC, thymikee commented on package.json
> +    "eslint-plugin-jest": "^27.0.1",
Not really expected, but historically ESLint had troubles with resolving some plugins that are imported by the configs. Never investigated why it happens, but apparently it still does in eslint@8 :D

2022-09-07 14:04 UTC, thymikee commented on src/components/__tests__/__snapshots__/TextInput.test.js.snap
> +      accessibilityLabel="Text input field"
@lukewalczak can you advise here? is TextInput already accessible enough or it needs the label?

2022-09-07 14:05 UTC, thymikee commented on .eslintrc
> +    "react-native-a11y/has-accessibility-hint": "off",
"react-native-a11y/has-accessibility-hint" is turned off by default in v13.0.1

2022-09-08 08:43 UTC, lukewalczak commented on src/components/__tests__/__snapshots__/TextInput.test.js.snap
> +      accessibilityLabel="Text input field"
Since under the hood there is a native input, we don't that label – it's built-in already.

2022-09-12 10:39 UTC, jaworek commented on .eslintrc
> +    "react-native-a11y/has-valid-accessibility-state": "off"
`accessibilityState={{ ...accessibilityState, disabled }}` in FAB.tsx and AnimatedFAB.tsx causes this rule to crash. If I extract creation of this object to variable, e.g.
```
const newAccessibilityState= { ...accessibilityState, disabled };
```

and then use it in component this way:
```
accessibilityState={newAccessibilityState}
```
It does not crash anymore. @thymikee, @lukewalczak, do you think this is a bug with this rule and should be reported to `react-native-a11y` repo?

2022-09-12 10:58 UTC, thymikee commented on .eslintrc
> +    "react-native-a11y/has-valid-accessibility-state": "off"
File a bug in react-native-a11y

2022-09-12 11:10 UTC, jaworek commented
After updating to newest callstack eslint config, I'm getting error that plugins are not present:
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/22678765/189638864-7f6b01d4-a298-4781-8213-5433f23ab3fd.png">

I was able to resolve it by recreating yarn.lock with new package versions. Unfortunately this causes around 18 errors in TS, that I haven't been able to resolve yet. :(

Here's the TS error output:
https://app.circleci.com/pipelines/github/callstack/react-native-paper/2736/workflows/5466e829-16e6-4bda-870a-5f8e79198a34/jobs/30088/parallel-runs/0/steps/0-105

2022-09-27 10:14 UTC, jaworek commented on .eslintrc
> +    "react-native-a11y/has-valid-accessibility-state": "off"
https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/issues/146

2022-09-27 12:07 UTC, Drakeoon requested changes
@jaworek Good stuff! I left a couple of comments in my review

2022-09-27 12:07 UTC, Drakeoon commented on example/src/DrawerItems.tsx
> +import { DrawerContentScrollView } from '@react-navigation/drawer';
I personally prefer the following import order:
1. React and React Native modules
2. External libraries
3. Internal files

I've played around and was able to achieve such sorting order, so it's a matter of decision whether we keep it like that or introduce the sorting order config. I'm pasting the change + preview below:

https://user-images.githubusercontent.com/24693481/192519655-2f296046-7d0f-44c3-af43-4a1ccda4466f.mov

Config:
![image](https://user-images.githubusercontent.com/24693481/192519855-132647d4-c95e-4bb8-9feb-b592b30247dc.png)

I believe the config could be simplified, but I basically took battle-tested one from one of my other applications

2022-09-27 12:07 UTC, Drakeoon commented on example/src/Examples/BannerExample.tsx
> +                accessibilityIgnoresInvertColors={true}
```suggestion
                accessibilityIgnoresInvertColors
```

2022-09-27 12:07 UTC, Drakeoon commented on example/src/Examples/BottomNavigationExample.tsx
> +            accessibilityIgnoresInvertColors={true}
```suggestion
            accessibilityIgnoresInvertColors
```

2022-09-27 12:29 UTC, jaworek commented on example/src/DrawerItems.tsx
> +import { DrawerContentScrollView } from '@react-navigation/drawer';
I'm fine with this change!

2022-09-27 13:02 UTC, Drakeoon commented on example/src/DrawerItems.tsx
> +import { DrawerContentScrollView } from '@react-navigation/drawer';
I added said config and updated the files across the project, LGTM!

2022-09-27 13:04 UTC, Drakeoon approved these changes

2022-09-27 15:58 UTC, lukewalczak commented
Thanks @jaworek and @Drakeoon for updating the eslint! 🔥

2022-09-27 15:58 UTC, merged