feat: use Pressable in TouchableRipple
callstack/react-native-paper pull request #3400
Opened 2022-10-05 04:50 UTC by szymonrybczak

This PR replaces `Touchables` with `Pressable` within `TouchableRipple`.

#### Related issues: 
- #3396 

### Summary

### Test plan

2022-10-12 07:31 UTC, hurali97 requested changes
Thanks for raising this PR, much appreciated 🌟.

There are a couple changes that can be addressed.

2022-10-12 08:05 UTC, hurali97 commented
@szymonrybczak Additionally, there are some regressions that causes instability on web. I am attaching the screenshots of the relevant components that are affected by the PR changes. If you can take a look at these, it will be so helpful.

### Platform(web):

- The back icon button mis aligns on web.

<details>
 <summary>Bottom-Navigation</summary>

 - layout of bottom-navigation shrinks on web.

<img width="1728" alt="Bottom-Navigation" src="https://user-images.githubusercontent.com/47336142/195279296-2ffab05e-14ce-4506-91d2-3f7c447642b9.png">
</details>

<details>
 <summary> Buttons </summary>

- Ripple doesn't respect the border-radius.

<img width="1542" alt="Buttons" src="https://user-images.githubusercontent.com/47336142/195279298-62729cae-191f-4bd5-a6f3-32eb33e96f9f.png">
</details>

<details>
 <summary>Icon-Buttons</summary>

- Doesn't center the icon correctly, and ripple only happens on icon, not the whole component.

<img width="915" alt="Icon-Buttons" src="https://user-images.githubusercontent.com/47336142/195279311-41f4ccef-6314-465b-83ba-93304468769c.png">
</details>

<details>
 <summary>Radio-Button-Group</summary>

- Ripple is not round, as compared to the baseline.

<img width="1728" alt="Radio-Button-Group" src="https://user-images.githubusercontent.com/47336142/195279324-148eafce-4e49-43b0-b3c0-47ae8a3bbe79.png">
</details>

<details>
 <summary> SearchBar </summary>

- Related to Icon Buttons.

<img width="1720" alt="SearchBar" src="https://user-images.githubusercontent.com/47336142/195279333-1726b4e1-ae98-48b8-9070-ddd1a201256f.png">
</details>

<details>
 <summary>Segmented-Buttons</summary>

- Related to the border-radius in Buttons.

<img width="1728" alt="Segmented-Buttons" src="https://user-images.githubusercontent.com/47336142/195279338-861da408-a129-4fd5-aaef-c34184a6a7aa.png">
</details>

<details>
 <summary>Text-Input</summary>

- Related to Icon Buttons.

<img width="1727" alt="Text-Input" src="https://user-images.githubusercontent.com/47336142/195279354-0b587949-8c02-4fad-be7e-fc2970a73fa9.png">
</details>

<details>
 <summary>Toggle-Buttons</summary>

- Ripple doesn't fill the container, it only fills the inner view.

<img width="1728" alt="Toggle-Buttons" src="https://user-images.githubusercontent.com/47336142/195279361-afa0c75d-beba-4f19-bd3a-48637996a8df.png">
</details>

<details>
 <summary>Touchable-Ripple-Difference</summary>
<br />
Touchable Ripple New:

<img width="1720" alt="Touchable-Ripple-New" src="https://user-images.githubusercontent.com/47336142/195279367-06144792-08f6-441c-bee7-1e0eb4a83104.png">

<br />
Touchable Ripple Baseline:

<img width="1721" alt="Touchable-Ripple-Old" src="https://user-images.githubusercontent.com/47336142/195279369-e5527ad7-3313-41fd-944a-4f957bde2b29.png">
</details>

2022-10-12 14:28 UTC, szymonrybczak commented on src/components/TouchableRipple/TouchableRipple.native.tsx
> +      onPressIn={(e: GestureResponderEvent) => {
Fixed ✅

2022-10-12 14:28 UTC, szymonrybczak commented on src/components/TouchableRipple/TouchableRipple.native.tsx
> +      onPressOut={(e: GestureResponderEvent) => {
Fixed ✅

2022-10-12 14:30 UTC, szymonrybczak commented
@hurali97 Yes, sure. This was really the problem, I fixed it! 😅

2022-10-12 15:15 UTC, hurali97 commented
@szymonrybczak Thanks for incorporating them real quick. 🌟

@lukewalczak I'll re-run the tests and re-review the PR tomorrow morning.

2022-10-13 06:41 UTC, hurali97 approved these changes

2022-10-17 08:29 UTC, lukewalczak approved these changes
Great work 🎉 Thanks @szymonrybczak for your effort and @hurali97 for reviewing and testing the PR!

2022-10-17 08:29 UTC, merged