feat: add customInputStyle to TextInput
callstack/react-native-paper pull request #3509
Opened 2022-12-07 02:09 UTC by guilherme-ferraz1

### Summary

Adds `customInputStyle` prop to `TextInput` as requested in #3434 
This prop allows to pass style props directly to the input itself, not the container. 

### Test plan

The tests and examples are already updated.
Tested on both IOS and Android with `StyleProp<ViewStyle>` props like `paddingLeft`, `backgroundColor` etc.

**Custom style input example:**

`customInputStyle={{ paddingLeft: 50  }}`

<img width="339" alt="Captura de Tela 2022-12-06 às 23 06 18" src="https://user-images.githubusercontent.com/62260157/206069984-0e4776fd-0105-4637-8c2f-c029cfd3b61d.png">

2022-12-16 19:52 UTC, gmferraz commented on src/components/TextInput/TextInput.tsx
> +  customInputStyle?: StyleProp<ViewStyle>;
sure

2022-12-16 19:52 UTC, gmferraz commented on src/components/TextInput/TextInput.tsx
> +      customInputStyle = null,
fixed

2022-12-16 19:54 UTC, gmferraz commented
@lukewalczak unit test added, prop name changed and minor issues fixed

2022-12-18 20:49 UTC, lukewalczak commented
Hey @gmferraz, I've analyzed your PR one more time and have two requests, please:

* resolve conflict
* rename prop to `contentStyle` - it's more appropriate than `containerStyle` proposed previously.

I would like to do the release tomorrow, so please handle it if possible 🙏🏽

2022-12-18 21:31 UTC, gmferraz commented
@lukewalczak done :)

2022-12-18 21:50 UTC, lukewalczak requested changes

2022-12-18 21:50 UTC, lukewalczak commented on src/components/TextInput/TextInputFlat.tsx
> +  const contentStyle = {
I think it should not be changed.

2022-12-18 21:50 UTC, lukewalczak commented on src/components/TextInput/TextInputFlat.tsx
> +    <View style={[contentStyle, viewStyle]}>
The same here.

2022-12-18 21:50 UTC, lukewalczak commented on src/components/TextInput/TextInputFlat.tsx
> +                  viewStyle.backgroundColor || contentStyle.backgroundColor,
And there as well.

2022-12-18 21:50 UTC, lukewalczak commented on src/components/TextInput/TextInputFlat.tsx
> +  contentStyle: customContainerStyle,
```suggestion
  contentStyle,
```

2022-12-18 21:50 UTC, lukewalczak commented on src/components/TextInput/TextInputFlat.tsx
> +            customContainerStyle,
```suggestion
            contentStyle,
```

2022-12-18 23:03 UTC, gmferraz commented on src/components/TextInput/TextInputFlat.tsx
> +            customContainerStyle,
oops I guess it should be fine now

2022-12-19 08:40 UTC, lukewalczak approved these changes

2022-12-19 08:40 UTC, merged