Made ToggleButton.Group TS compatible
callstack/react-native-paper pull request #3543
Opened 2022-12-21 09:07 UTC by gedu

fix: Now you can use `ToggleButton.Group` with Union Types and Enums (default string)

### Summary

Before you couldn't use Union types or enums without TS complaining about the type

```
type Fruits = 'watermelon' | 'strawberries' | 'apple';
```
<img width="679" alt="ts_error_type_string" src="https://user-images.githubusercontent.com/1676818/208864169-5ec3bb78-dc43-4f37-ab10-c3b17f582a5a.png">

with this new change, TS will get the right type and won't complain

<img width="873" alt="new_toggleButton_unionT_function" src="https://user-images.githubusercontent.com/1676818/208864686-d6ec1951-2469-44d5-81fc-296761cd265f.png">

### Test plan

- Use different types, like string, enums and union types
- Check if the IDE get the right type

2022-12-21 10:51 UTC, satya164 requested changes

2022-12-21 10:51 UTC, satya164 commented on src/components/ToggleButton/ToggleButtonGroup.tsx
> +export type Props<TData = string> = {
We don't use `T` prefix for types. For regular types that user will encounter, prefer using just the name of the thing it represents (e.g. `Value`), or for generic types like this one just `T` is preferable.

2022-12-21 10:51 UTC, satya164 commented on src/components/ToggleButton/ToggleButtonGroup.tsx
> +  onValueChange: (value: TData) => void | null;
Unrelated to this specific change, but `void | null` seems wrong. It shouldn't matter whether `onValueChange` returns `null` or something else

2022-12-21 10:51 UTC, satya164 commented on src/components/ToggleButton/ToggleButtonGroup.tsx
> +type ToggleButtonContextType<TData = any> = {
I don't think it's possible to infer this generic for context so probably better not to use generic. We should also avoid using `any` as it makes it easy to spread and make code unsafe. Prefer ignoring the type error explicitly when necessary instead.

2022-12-21 14:07 UTC, gedu commented on src/components/ToggleButton/ToggleButtonGroup.tsx
> +type ToggleButtonContextType<TData = any> = {
This one is hard to infer but I need the generic to handle the Consumer function, if not I get a type error. Agreed to avoid `any`, if ignoring is the preferred way I will add it.

2022-12-21 14:16 UTC, satya164 commented on src/components/ToggleButton/ToggleButtonGroup.tsx
> +type ToggleButtonContextType<TData = any> = {
> I need the generic to handle the Consumer function, if not I get a type error

The type error is valid since there's no way to ensure that the type from the group will match the type of value in the individual buttons. In this case, suppressing the error with a comment will be more explicit.

2023-01-05 10:00 UTC, jaworek commented on src/components/ToggleButton/ToggleButtonGroup.tsx
> +  //@ts-ignore: so we avoid using `any`, TS can't ensure the type from Group to children
```suggestion
  //@ts-expect-error: TS can't ensure the type from Group to children
```

2023-01-09 15:49 UTC, lukewalczak approved these changes

2023-01-09 15:52 UTC, jaworek approved these changes

2023-01-09 15:56 UTC, merged