docs: add react-native-web support plugin
callstack/react-native-paper pull request #3630
Opened 2023-01-29 13:52 UTC by yamankatby

### Summary
- Created a Docusaurus plugin to run `react-native` components (using React Native for the Web)
- Added a simple components overview example

https://user-images.githubusercontent.com/35961879/215330302-f8cbf7b2-7fba-4718-be86-71b6e521ae19.mov

### Test plan

2023-01-30 10:22 UTC, Drakeoon requested changes
Overall the changes look good, however please take a look at one comment I've left

2023-01-30 10:42 UTC, yamankatby commented on docusaurus/package.json
> +    "react-native-paper": "^5.1.4",
hmmm, taking a look 👀

2023-01-30 11:08 UTC, yamankatby commented on docusaurus/package.json
> +    "react-native-paper": "^5.1.4",
well, we are good now 🔥

2023-01-30 11:21 UTC, lukewalczak commented
@yamankatby looks like the build is not passing currently, please take a look 🙏🏽

2023-01-30 12:04 UTC, yamankatby commented
@lukewalczak @Drakeoon, all done take a look 👀

2023-01-30 12:09 UTC, lukewalczak commented
Awesome, changes looks good! I will try to play with it in the evening and then merge ✌🏽

2023-01-30 19:20 UTC, lukewalczak commented
I've just run docs locally and while on google chrome I don't see any problems, icons don't load on the safari:

<img width="884" alt="image" src="https://user-images.githubusercontent.com/22746080/215574798-78761f68-7510-45fc-abf4-3bb8e19a9b3a.png">

2023-01-31 07:21 UTC, yamankatby commented
I'll take a look 👀

2023-01-31 08:43 UTC, yamankatby commented
Hey @lukewalczak,
Well, looks ok here. I'm not sure what could it be, maybe a hard refresh can make it, if not can you please see if any logs in the console?

![Screenshot 2023-01-31 at 11 40 38](https://user-images.githubusercontent.com/35961879/215710603-4bda409c-2208-4205-a58e-2e51f97f2155.png)

2023-02-03 08:48 UTC, lukewalczak commented
Tested again on mobile and web Safari browsers and the result is satisfying. Thanks for adjusting all the requests!

2023-02-03 08:49 UTC, lukewalczak approved these changes

2023-02-03 08:49 UTC, merged