feat Add onClearIconPress to SearchBar
callstack/react-native-paper pull request #3679
Opened 2023-02-15 00:12 UTC by n0tl3ss

### Summary

This PR adds the `onClearIconPress' prop to the `Searchbar' component. If `onClearIconPress` is defined when pressing close button on search the default behaviour will be executed and after that users' hook will be executed. This for an example allows `Keyboard.dismiss()` to be called from hook.
### Test plan

There is no visually changes. Adding 
`  onClearIconPress={() => /* delete query text (default behaviour) and dismiss keyboard */ Keyboard.dismiss()}` to ` SearchBar` should dismiss keyboard after clearing text.

This feature was requested in #1970

2023-02-19 19:51 UTC, lukewalczak requested changes

2023-02-19 19:51 UTC, lukewalczak commented on src/components/Searchbar.tsx
> +      onClearIconPress?.(e);
In order to accept the PR please add an unit test confirming that `onClearIconPress` is called when clear button is pressed

2023-03-06 09:06 UTC, n0tl3ss commented
Hi @lukewalczak thanks for your reply. Sorry for late response I was on vacation. I think now everything is ready.

2023-03-06 09:15 UTC, lukewalczak commented
Hey @n0tl3ss, thanks for PR adjustments. Please correct the commit message in order to merge it _(according to the contribution guide)._

2023-03-06 09:46 UTC, n0tl3ss commented
Hi, @lukewalczak. Is commit message now ok? :)

2023-03-06 10:02 UTC, lukewalczak approved these changes
Thanks @n0tl3ss for addressing the feedback and adding a new functionality!

2023-03-06 10:08 UTC, lukewalczak commented
The commit message is still not correct, it should be `feat: ...` _(missing colon)_

2023-03-06 10:39 UTC, n0tl3ss commented
@lukewalczak can you please rerun `Semantic Pull Request / Validate PR title (pull_request)` I changed title of this PR. Sorry for troubles :)

2023-03-06 11:33 UTC, merged