chore: use TS generics for BottomTab types
callstack/react-native-paper pull request #3741
Opened 2023-03-10 12:26 UTC by tjaniczek

### Summary

This PR switches `BottomNavigation` implementation to use generic type instead of hardcoded `Route`.

Due to the fact that `BottomNavigation.Bar` may be used with any router, we should not force users to adhere to Material's generic types. As long as all methods passed to `BottomNavigation.Bar` are type safe the user should be able to define (or import from chosen router) the type himself.

This change is also required as a preparation for integration with React Navigation 7, that has two breaking changes related to `MaterialBottomTabView`:
- removal of `useLinkBuilder`
- removal of `key` in `onTabPress` events

There should be no changes to JS users. For TS users `BottomNavigation` should now correctly infer types in handlers (`onTabPress`, `getLabelText` and so on) - but if they used custom `Route` type previously - they had to disable type checking in their code anyway 🤷 

Tested in both React Native 6 & 7, docs updated, added test to document the behaviour.

### Test plan

It would be nice to install it on real-world app and see if everything works as expected.

2023-03-10 12:52 UTC, satya164 requested changes

2023-03-10 13:03 UTC, tjaniczek commented on example/src/Examples/BottomNavigationBarExample.tsx
> +        <BottomNavigation.Bar<Route<keyof ParamListBase>>
I tried something along `Props['state']['routes'][number]` but since it's an internal implementation the above would suffice. Also, I think this makes it easier to understand in docs

2023-03-10 13:21 UTC, tjaniczek commented on src/components/BottomNavigation/BottomNavigation.tsx
> +type NavigationState<TRoute extends Route> = {
Was thinking even about a further split:
```
type BaseRoute = { key: string };
type DefaultRoute = BaseRoute & { title?: string, focusedIcon?: string ... };

const BottomNavigation = <Route extends BaseRoute = DefaultRoute>({ ...
```

Wdyt?

2023-03-10 14:46 UTC, satya164 commented on src/components/BottomNavigation/BottomNavigation.tsx
> +type NavigationState<TRoute extends Route> = {
I'm not sure if it can be split like that given `BottomNavigation` accesses those properties on `route`, and not having them may cause type errors.

2023-03-10 14:47 UTC, satya164 commented on example/src/Examples/BottomNavigationBarExample.tsx
> +        <BottomNavigation.Bar<Route<keyof ParamListBase>>
> I tried something along Props['state']['routes'][number] but since it's an internal implementation the above would suffice. Also, I think this makes it easier to understand in docs

I mean automatic inference without any manual type annotations

2023-03-13 12:17 UTC, tjaniczek commented on src/components/BottomNavigation/BottomNavigation.tsx
> +type NavigationState<TRoute extends Route> = {
All but `key` are optional and used only in callbacks so if you provide different shape you'll need to provide own callbacks too

2023-03-13 12:28 UTC, tjaniczek commented on example/src/Examples/BottomNavigationBarExample.tsx
> +              navigation.navigate(route.name);
Thanks, updated

2023-03-13 12:43 UTC, satya164 commented on example/src/Examples/BottomNavigationBarExample.tsx
> +        <BottomNavigation.Bar<Route<keyof ParamListBase>>
@tjaniczek I'm not sure if I understood the problem. In your snippet seems like you're writing code for inference so it's not automatic. By automatic inference, I mean that TypeScript will automatically infer the type of `route` without additional work since it's a generic which is used in the props.

I just pulled the code and remove the explicit annotation of the generic, and TS does seem to infer the type automatically based on the type of `route` in `navigationState` prop:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/1174278/224705320-0eb9b67f-b4dd-4438-90a0-09c06d1cb2e9.png">


<img width="665" alt="image" src="https://user-images.githubusercontent.com/1174278/224705190-eed88ba2-84e1-4c1a-a966-22096c42569e.png">

2023-03-13 12:46 UTC, satya164 commented on src/components/BottomNavigation/BottomNavigation.tsx
> +type NavigationState<TRoute extends Route> = {
@tjaniczek it's not about them being optional. not having them in the `route` object means you cannot do `route.color` etc. since TS will complain that `color` property doesn't exist. Such code is used in `BottomNavigation` already which will type-errors.

2023-03-14 09:46 UTC, tjaniczek commented on example/src/Examples/BottomNavigationBarExample.tsx
> +        <BottomNavigation.Bar<Route<keyof ParamListBase>>
Hello @satya164 , found the offender:
https://github.com/callstack/react-native-paper/pull/3741/files#diff-c52aaae04c874f08a9d79b95c7263844b25df21606f6250777f2e3754b626800R37

Spreading props results in TS not being able to infer types. This little hack fixes it, although passing generic is what I suggested in docs: https://github.com/callstack/react-native-paper/pull/3741/files#diff-ac8f9da8cbc036504635455603d1faacb546641d2e8cb7f8d85cbc84551bd9b4R319

Now everything is being inferred correctly by TS engine 👍

2023-03-14 09:51 UTC, tjaniczek commented
State for now:
- `BottomNavigation` allows custom `state` and properly infers `Route` state from the passed props
- `BottomNavigation.Bar` allows custom `state` and properly infers `Route` state from the passed props
- passing explicit `Route` shape is available when automatic inference is not possible
- above behaviour documented in docs
- works in RN6 & RN7.0.0-alpha.1 (with small change `useLinkBuilder` -> `useLinkTools`)
- added test to check custom `Route` shape

2023-03-14 09:54 UTC, tjaniczek commented on src/components/BottomNavigation/BottomNavigationBar.tsx
> + *               navigation.navigate(route.name, route.params);
Changed to `navigation.dispatch()` to make it work with RN7 as well

2023-03-14 10:01 UTC, lukewalczak commented on src/components/BottomNavigation/BottomNavigation.tsx
> + * ## Usage with TypeScript
The ultimate goal for new docs is to introduce tabs `JS` and `TS` similar to `npm` and `yarn` so users can switch between those two and check which fit more for them.

cc: @DimitarNestorov _(as far as I remember you were asking for that)_

At the moment, since it's not available, maybe we can take advantage of my other [PR](https://github.com/callstack/react-native-paper/pull/3747) introducing "More Examples" , wdyt?

2023-03-14 10:06 UTC, tjaniczek commented on src/components/BottomNavigation/BottomNavigation.tsx
> + * ## Usage with TypeScript
Agreed, will change it as soon as Portal docs land in `main` 👍

2023-03-15 10:23 UTC, DimitarNestorov commented on src/react-navigation/adapter.ts
> +  typeof useLinkTools !== 'undefined' ? useV7Link : useV6Link;
I'd remove `useV6Link`
```suggestion
export const useNavigationLink: NavigationLink =
  typeof useLinkTools !== 'undefined' ? useV7Link : useLinkBuilder;
```
Also can you add a comment:
> In React Navigation 7 `useLinkBuilder` was superseded by `useLinkTools`
> https://reactnavigation.org/docs/7.x/upgrading-from-6.x/#the-uselinkto-and-uselinkbuilder-hooks-are-merged-into-uselinktools

2023-03-15 12:23 UTC, tjaniczek commented on src/react-navigation/adapter.ts
> +  typeof useLinkTools !== 'undefined' ? useV7Link : useV6Link;
Thanks, updated

2023-03-15 13:48 UTC, tjaniczek commented on src/components/BottomNavigation/BottomNavigation.tsx
> + * ## Usage with TypeScript
Done: https://snack.expo.dev/@react-native-paper/bottomnavigation---usage-with-typescript

Please note that this snack will show warning at the moment, since this change is not merged yet. We'll need to update dependency in the snack when this change gets released 👍

2023-03-20 06:36 UTC, DimitarNestorov commented on example/src/Examples/BottomNavigationBarExample.tsx
> +        <BottomNavigation.Bar<Route<keyof ParamListBase>>
With this type assertion we lose type checking on `rest`. The issue is caused by `getLazy`. Might not be the best way to fix it but it worked for me:

1. Revert the type assertion on `rest`
2. `src/react-navigation/types.tsx`: Also omit `getLazy` in `MaterialBottomTabNavigationConfig`
3. `src/react-navigation/views/MaterialBottomTabView.tsx`: Modify `MaterialBottomTabNavigationConfig`:
    ```diff
     type Props = MaterialBottomTabNavigationConfig & {
       state: TabNavigationState<ParamListBase>;
       navigation: MaterialBottomTabNavigationHelpers;
       descriptors: MaterialBottomTabDescriptorMap;
    +  getLazy?: (props: {
    +    route: TabNavigationState<ParamListBase>['routes'][number];
    +  }) => boolean | undefined;
     };
    ```

2023-03-20 11:41 UTC, DimitarNestorov approved these changes

2023-03-20 13:22 UTC, merged