fix: rtl not being detected correctly on web
callstack/react-native-paper pull request #3777
Opened 2023-03-23 10:00 UTC by pac-guerreiro

### Summary

RTL detection didn't work on web because RN I18nManager only works on native.

My solution was to use `navigator.language` to extract the current browser language and check if it is included on the list of RTL languages (which I extracted from react-native-web).

While this approach works well on Chrome and Safari, I did notice that on Firefox it won't detect the correct language when there are two default languages, but nonetheless it should pick the one which is the native language of the user.

### Test plan

Run the web version of the example app on any browser using Hebrew or Arabic language, for example, and check Progress Bar example.

**Firefox**:
<img width="1351" alt="Screenshot 2023-03-22 at 19 22 27" src="https://user-images.githubusercontent.com/48553277/227167989-56867319-bb3d-4905-b8e0-4900abe08eef.png">

**Safari**:
<img width="1352" alt="Screenshot 2023-03-22 at 19 23 07" src="https://user-images.githubusercontent.com/48553277/227167995-02d77d9f-549b-4dc4-94fe-c78fa6a4e95d.png">

**Chrome**:
<img width="1352" alt="Screenshot 2023-03-22 at 19 25 00" src="https://user-images.githubusercontent.com/48553277/227167998-54c3bda5-6f8c-4fb8-8205-21ed722f8ab6.png">

2023-03-30 06:25 UTC, DimitarNestorov requested changes

2023-04-01 16:06 UTC, DimitarNestorov commented on src/core/Provider.tsx
> +                <View style={styles.container} {...{ dir: direction }}>
This container View can be considered a breaking change. I believe we should revert this change and just add a note in the docs and add it in the Example app. It's something specific to react-native-web. Thoughts @lukewalczak @tjaniczek?

2023-04-02 13:03 UTC, lukewalczak commented on src/core/Provider.tsx
> +                <View style={styles.container} {...{ dir: direction }}>
> I believe we should revert this change and just add a note in the docs and add it in the Example app. It's something specific to react-native-web.

Thanks @DimitarNestorov for your input! Could you please elaborate more on your suggestion?

2023-04-02 15:37 UTC, DimitarNestorov commented on src/core/Provider.tsx
> +                <View style={styles.container} {...{ dir: direction }}>
I read from the description of the PR that the `dir` prop of the wrapping `View` is what fixes RTL on web. This wrapping View can be a problem for some. Even conditionally rendering it only for web can be a problem, so we should instead document it well and link people to the docs.

2023-04-14 08:45 UTC, tjaniczek commented
Not sure why the pop-up menu is still LTR on web:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/7429558/231992765-67134266-dcf3-4daf-9658-f0fba92d3d2d.png">

will pick up this task for the time being. Also, I like @DimitarNestorov approach 👍  removed the `View` already and added docs instead

2023-04-14 10:44 UTC, tjaniczek commented on src/core/Provider.tsx
> +                <View style={styles.container} {...{ dir: direction }}>
`dir` is not a valid prop for RN's `View`.  This wired notation `{...{ dir: direction }}` is there only to avoid TS error. We should get rid of it anyway.

I think the original idea for `react-native-web` was to wrap the whole app in `<html dir="rtl">` - I tested that and it makes much more sense, we'll avoid this additional wrapper, problems with Portals etc. Will rework the `Localization` provider and figure out better API to support this.

2023-04-18 13:01 UTC, tjaniczek commented
Ok, since this PR becomes too ridiculous to review I'll try to pinpoint a couple of issues.

First things first, `react-native-web` mocks out the whole `I18nManager` and relies text positioning on `dir` property of parent element (e.g. `<View dir="rtl>`). As far as I know, RN does not support this property so linter throws error trying to use it. Effectively there's no way around it so I added [this convenient wrapper](https://github.com/callstack/react-native-paper/pull/3777/files#diff-696727b69da6b034a61ac170db640d76426194d7e535d6df3873b6765f777fd6R37) to silent the linter. With or without this, there's the key problem:

**Since `react-native-web` parses RTL layouts differently to `RN` we will need to support two ways of defining LTR/RTL layouts** (web & mobile).

Most concerns I have regard [this useEffect](https://github.com/callstack/react-native-paper/pull/3777/files#diff-df7f1205b408a8b779895c080c77457728df4da79a0fa852c0255e54ce897664R83) where I'd assign dir to the root `<html>` element of a page (`<html dir="rtl">`). This handles most cases since the `react-native-way` looks all the way to the top of the tree to find this prop. Without top element with `dir` attribute we'd have to add this in multiple places: 
- below `<Provider>` , 
- in each `<Modal>` 
- and as far as I know inside each `<Surface>` too

Surprisingly, this is not a breaking change, since to apply this `direction` has to be manually passed into `<Provider>` ( [as explained here](https://github.com/callstack/react-native-paper/pull/3777/files#diff-bffc8ea6fc2d7dbf6593758d46277634fb9645efd8ad56d97642f189dd642069R273) ) , and the prop itself is added in this PR.

Other than that, we need a few hacks since we're basically retrofitting the RTL support at this point:
- https://github.com/callstack/react-native-paper/pull/3777/files#diff-46327c8e0610e196d2eec4ef16e3fee3fe0b9f69c0451f9e43e331b7f26ed08bR163
- https://github.com/callstack/react-native-paper/pull/3777/files#diff-40a7ac238bd91da69419785da41b78053017736cab9ece62b22639c8537174e2R61
- https://github.com/callstack/react-native-paper/pull/3777/files#diff-a4dba4502c98f41455802b906263f5842e6a67881b016e03d6d8a9b5718dcbe7R8
- https://github.com/callstack/react-native-paper/pull/3777/files#diff-5146ee7e7b0598cc2982fcdd8c7f9f6cd3eb0d891f87203ebfc5a3255a6d24beR82

And there's also a couple things I couldn't get to work properly:
- `Animated FAB` does not work on web at the moment (both LTR and RTL are broken)
- `Material Bottom Tab Navigator` does not turn the content RTL automatically (need to investigate RTL support in Navigator)
- `TextInput` - absolutely no way of getting this component to work on both web & mobile RTL

2023-04-19 07:22 UTC, satya164 commented
> Most concerns I have regard [this useEffect](https://github.com/callstack/react-native-paper/pull/3777/files#diff-df7f1205b408a8b779895c080c77457728df4da79a0fa852c0255e54ce897664R83) where I'd assign dir to the root <html> element of a page (<html dir="rtl">). This handles most cases since the react-native-web looks all the way to the top of the tree to find this prop.

This won't work with SSR on Web. What I'm planning for React Navigation is to ask users to pass `dir` to HTML and call `I18nManager.forceRTL` if they need to support `RTL`. The `direction` prop on the `Provider` is simply to inform the library about which direction needs to be used. The library itself shouldn't be trying to call `I18nManager.forceRTL` or mutate the DOM. Doing that affects far more than the library's scope.

Other than that on React Navigation side the changes are essentially replacing usage of `I18nManager` with the `direction` from `Provider`.

2023-08-03 10:57 UTC, pac-guerreiro commented
Can I close this PR?

2023-08-03 10:58 UTC, tjaniczek commented
No, huge chunk of work left

2023-12-29 10:57 UTC, federicogomezlara commented
Hello, do you guys plan to continue to work on this feature? We'd love to be able to use it, we've had to swap out our texts and inputs for others from other library on web

2024-02-17 19:05 UTC, arasrezaei commented
lots of stuff has to be done!

2026-05-13 16:21 UTC, satya164 commented
Closing in favor of https://github.com/callstack/react-native-paper/pull/4921

2026-05-13 16:21 UTC, closed without merging