feat: support for maxFontSizeMutliplier on Checkbox.Item
callstack/react-native-paper pull request #3791
Opened 2023-03-30 09:42 UTC by dimitrisspacecode

### Summary

Added max font scaling support for the Checkbox.Item component

### Test plan

Easy way to test it is by running the example on an iOS simulator and start Increasing/Decreasing the Preferred Text Size (on default I set it to 0, meaning it's disabled, set it to 1.1 or more to test it works)

2023-04-03 11:39 UTC, lukewalczak commented on src/components/Checkbox/CheckboxItem.tsx
> +          maxFontSizeMultiplier={maxFontSizeMultiplier}
Please add unit test covering new prop

2023-04-03 11:41 UTC, lukewalczak commented on src/components/Checkbox/CheckboxItem.tsx
> +  maxFontSizeMultiplier = 0,
I think we should add at least `1.5` as a default value, like in other places.

2023-04-04 11:07 UTC, DimitarNestorov requested changes

2023-04-04 11:07 UTC, DimitarNestorov commented on src/components/__tests__/Checkbox/CheckboxItem.test.tsx
> +    checkboxItem.props.children[0].props.children[1].props.maxFontSizeMultiplier
Add a `testID` to the `Text` in the checkbox.
```diff
         <Text
           variant={labelVariant}
           maxFontSizeMultiplier={maxFontSizeMultiplier}
+          testID={`${testID}-text`}
```

And then update the test

```suggestion
  const checkboxItemText = getByTestId('checkbox-item-text');
  expect(
    checkboxItemText.props.maxFontSizeMultiplier
```

2023-04-04 12:07 UTC, DimitarNestorov approved these changes

2023-04-17 11:51 UTC, merged

2023-04-17 12:05 UTC, lukewalczak commented
I've created an additional [commit](https://github.com/callstack/react-native-paper/commit/e77119759b152509e367a2e430a5c346997c6063) to rename the `maxFontSizeMultiplier` to `labelMaxFontSizeMultiplier` to keep the consistency with other props related to the same component such as `labelStyle` or `labelVariant`