fix: correct the way how disabling touchable is handled
callstack/react-native-paper pull request #3803
Opened 2023-04-05 18:50 UTC by lukewalczak

Fixes: https://github.com/callstack/react-native-paper/issues/3303

### Summary

Introducing hook `useIsTouchableEvent` to check whether any touchable event was passed to the `TouchableRipple` to properly set `disabled` prop.

Context: 

I guess touchable was initially disabled when `onPress` callback is not defined, in order to prevent running custom functionality handled by onPressIne.g. in Button [component](https://github.com/callstack/react-native-paper/blob/main/src/components/Button/Button.tsx?rgh-link-date=2022-09-23T12%3A45%3A14Z#L208). Probably the same applies to the Chip component.

#### Related issue:

- #3303 

### Test plan

- [X] - covered new hook with unit test
- [ ] - write unit test in `Chip` and `Button` component to confirm that `disabled` is properly set

2023-04-06 08:35 UTC, DimitarNestorov commented
Why a hook?

```ts
const hasTouchHandler = (...events: (event: GestureResponderEvent) => void) =>
  Boolean(events.filter(Boolean).length);
```

Usage:
```ts
const hasPassedTouchHandler = hasTouchHandler(
  onPress,
  onLongPress,
  onPressIn,
  onPressOut,
);

// disabled={disabled || !hasPassedTouchHandler}
```

2023-04-06 10:16 UTC, lukewalczak commented
> Why a hook?

Tbh there is no specific reason, just creating a hook came to my mind. Creating simple util helper makes sense as well and most likely will be faster and less complicated 🙌🏽 
I will refactor it, thanks!

2023-04-07 08:51 UTC, DimitarNestorov requested changes

2023-04-07 08:51 UTC, DimitarNestorov commented on src/utils/hasTouchHandler.tsx
> +): boolean => {
```suggestion
export default function hasTouchHandler(
  touchableEventObject: TouchableEventObject
) {
```

2023-04-07 08:51 UTC, DimitarNestorov commented on src/utils/hasTouchHandler.tsx
> +};
Move the `touchableEvents` array out of the function and mark it as const and then update the type:
```suggestion
type TouchableEventObject = Partial<Record<keyof touchableEvents[number], (event: GestureResponderEvent) => void>>;
```
<img width="632" alt="image" src="https://user-images.githubusercontent.com/8790386/230576288-3d05be25-1818-4e3c-a564-c3df16ad62c0.png">

2023-04-07 09:03 UTC, DimitarNestorov requested changes

2023-04-07 14:11 UTC, DimitarNestorov approved these changes

2023-04-17 13:06 UTC, merged