fix: no longer spread key prop on BottomNavigationBar - resolves #4401
callstack/react-native-paper pull request #4494
Opened 2024-09-12 23:28 UTC by nick42d

### Motivation
Resolves #4401 with suggested fix from @CommanderRedYT

### Related issue
#4401

### Test plan
Tested following contribution guidelines https://github.com/callstack/react-native-paper/blob/main/CONTRIBUTING.md

2024-10-10 02:43 UTC, hello-ccchen commented
any update?

2024-10-12 11:46 UTC, prageeth commented
We are waiting for this too, would be great to have this merged and included in the next release. Thanks

2024-11-07 23:48 UTC, skoolaidl commented
Is this going to get merged?

2024-11-13 17:35 UTC, shuffledex commented
come on guys! launch a new release asap!

2024-12-01 23:40 UTC, elibroftw requested changes

2024-12-01 23:40 UTC, elibroftw commented on src/components/BottomNavigation/BottomNavigationBar.tsx
> +    <Touchable key={key} {...props} />
> 'key' is specified more than once, so this usage will be overwritten.

I suggest just keeping it at one line

```tsx
renderTouchable = (props: TouchableProps<Route>) => <Touchable {...props} key={props.key} />
```

2024-12-01 23:44 UTC, CommanderRedYT commented on src/components/BottomNavigation/BottomNavigationBar.tsx
> +    <Touchable key={key} {...props} />
You sure this works? `props` will still contain the key, so not sure if react will stop complaining when it is not split

2024-12-01 23:49 UTC, elibroftw commented on src/components/BottomNavigation/BottomNavigationBar.tsx
> +    <Touchable key={key} {...props} />
Have you never added duplicate props to a component? The last prop takes precedence. Also the error is a Typescript error visible in an IDE. I'm also already using this code in production since I didn't want the ripples that used to be present in the bottom tabs:

```jsx
renderTouchable={props => (
            <TouchableWithoutFeedback {...props} key={props.key} >
              <View {...props} key={props.key} />
            </TouchableWithoutFeedback>
          )}
```

2024-12-04 14:27 UTC, nick42d commented on src/components/BottomNavigation/BottomNavigationBar.tsx
> +    <Touchable key={key} {...props} />
> > 'key' is specified more than once, so this usage will be overwritten.
> 
> I suggest keeping it at one line
> 
> ```tsx
> renderTouchable = (props: TouchableProps<Route>) => <Touchable {...props} key={props.key} />
> ```

This seems like a bit of a nitpick to me. Is this required?

2024-12-04 14:38 UTC, ChromeQ commented on src/components/BottomNavigation/BottomNavigationBar.tsx
> +    <Touchable key={key} {...props} />
Surely it is better to destructure the props and avoid any potential duplicate keys, as the initial suggestion suggests, who cares if it spreads onto 2 lines rather than one, it's just source code and makes no difference to the published and production code.

2024-12-19 19:14 UTC, seanblonien commented on src/components/BottomNavigation/BottomNavigationBar.tsx
> +    <Touchable key={key} {...props} />
I have tested this with `patch-package` and it works and gets rid of the error. idk what y'all are going on about but this looks great and we need to merge it so we don't have to patch the library

here is exactly my `patch-package` for proof:
```diff
diff --git a/node_modules/react-native-paper/src/components/BottomNavigation/BottomNavigationBar.tsx b/node_modules/react-native-paper/src/components/BottomNavigation/BottomNavigationBar.tsx
index 0bfe303..0195d70 100644
--- a/node_modules/react-native-paper/src/components/BottomNavigation/BottomNavigationBar.tsx
+++ b/node_modules/react-native-paper/src/components/BottomNavigation/BottomNavigationBar.tsx
@@ -360,7 +360,9 @@ const BottomNavigationBar = <Route extends BaseRoute>({
   navigationState,
   renderIcon,
   renderLabel,
-  renderTouchable = (props: TouchableProps<Route>) => <Touchable {...props} />,
+  renderTouchable = ({key, ...props}: TouchableProps<Route> & { key: string }) => (
+    <TouchableRipple key={key} {...props} />
+  ),
   getLabelText = ({ route }: { route: Route }) => route.title,
   getBadge = ({ route }: { route: Route }) => route.badge,
   getColor = ({ route }: { route: Route }) => route.color,
```

2024-12-20 09:21 UTC, hello-ccchen commented
any update? 🥹

2024-12-22 22:18 UTC, lourencorodrigo commented
Please guys. Launch a new release with this fix.

2024-12-28 15:18 UTC, dribble-njr commented
wait a release~

2025-01-03 11:40 UTC, RSginer commented
could you merge this? @callstack-bot

2025-01-06 17:25 UTC, artiphishle commented on src/components/BottomNavigation/BottomNavigationBar.tsx
> +    <Touchable key={key} {...props} />
duplicate props not possible. ...props is used as a ...rest param and 'key' is properly stripped out of props therefore. 
....and use prettier if you fight about one or two lines. this issue is open since 10. of Decembre 24 and Android drops a error because key is spreaded into the props, forcing all dev's to patch

2025-01-06 18:24 UTC, artiphishle commented
Severity high possible please?
I mean 100% of devices (iOS & Android) not able to use the `<BottomNavigation />` and it looks like solved already. Maybe the discussion can be a follow-up task.

2025-01-06 18:33 UTC, artiphishle commented on src/components/BottomNavigation/BottomNavigationBar.tsx
> +    <Touchable key={key} {...props} />
@nick42d nope. as you correctly see, the `...props` is used as a `...rest` param, therefore the 'key' is stripped away from it, and there are no duplicated keys anyway. ES2015.
@ChromeQ 'potential duplicate keys'. really wonder if such a thing exists.

2025-02-04 07:51 UTC, StevenMartinMedgate commented
Is there news on this?

2025-02-11 12:36 UTC, ChromeQ commented
This PR can be closed now, turns out this is fixed (although not in isolation or from an existing PR)
I can confirm it works without warning on the latest version.

https://github.com/callstack/react-native-paper/commit/77d3af73a2db020da4a2a90592a4eda030e2a2ee#diff-54d07d0dd9a891cd54e08e7642d895b92a592e9294af566460fa17dab475fa0eL363

2025-02-13 23:35 UTC, nick42d commented
> This PR can be closed now, turns out this is fixed (although not in isolation or from an existing PR) I can confirm it works without warning on the latest version.
> 
> [77d3af7#diff-54d07d0dd9a891cd54e08e7642d895b92a592e9294af566460fa17dab475fa0eL363](https://github.com/callstack/react-native-paper/commit/77d3af73a2db020da4a2a90592a4eda030e2a2ee#diff-54d07d0dd9a891cd54e08e7642d895b92a592e9294af566460fa17dab475fa0eL363)

Confirmed, Callstack merged this change as part of a larger PR as ChromeQ mentioned.

2025-02-13 23:35 UTC, closed without merging