fix: input label not visible on ios if multiline, fixes #4482
callstack/react-native-paper pull request #4497
Opened 2024-09-14 21:27 UTC by damianfilipek81

### Motivation

This PR solves this [issue](https://github.com/callstack/react-native-paper/issues/4482). "When focusing into a TextInput (when mode='flat'), the label disappears. It shows up normally when multiline=false, and this is only a problem on iOS."

### Related issue

[issue](https://github.com/callstack/react-native-paper/issues/4482)

### Test plan

I've checked it on ios simulator and android emulator, since example project is on expo 48 i cannot install it on my phone.
I've also updated `TextInput.test.tsx.snap` snapshot since tests were failing.

2024-10-07 23:35 UTC, iM-GeeKy commented
@gedu Is this planned to be merged? Still an issue in `5.12.5`.

2025-01-15 22:35 UTC, ericpoulinnz commented
@gedu @BogiKay any plans on merging this in now that new arch is supported?

2025-01-25 14:29 UTC, BogiKay requested changes
I tested the fix and works good, the issue is gone. I just found one little improvement that can be done. Beside that all good 👍

2025-01-25 14:29 UTC, BogiKay commented on src/components/TextInput/Label/InputLabel.tsx
> -      style={[StyleSheet.absoluteFill, styles.overflow]}
I don't think we need to apply `styles.labelContainer` twice. Can you get rid of it from line `147`?

2025-01-26 21:47 UTC, ericpoulinnz commented
Worth checking that this PR fixes the issue on web as well. Since I posted the issue (#4482) I found this also is a problem on web.

2025-01-27 10:43 UTC, BogiKay commented
@ericpoulinnz I tested it and the issue is gone on web as well

2025-02-06 21:46 UTC, BogiKay approved these changes

2025-02-06 21:48 UTC, merged

2025-03-18 19:50 UTC, ericpoulinnz commented
@BogiKay any chance a new version can be pushed out now that this fixed is merged in?